// Code generated by abstraction-idl from abstraction-storage/content.thrift. DO NOT EDIT.

// abstraction.storage.content: declarations for index.mjs.

/** The frame transport a generated client calls: a facade binding or a connector's transport. */
interface FrameTransport {
  exchangeFrame(frame: Uint8Array): Promise<Uint8Array>;
  writeFrame(frame: Uint8Array): Promise<void>;
}

export type AbortOutcome = (typeof AbortOutcome)[keyof typeof AbortOutcome];
export declare const AbortOutcome: Readonly<{ Aborted: "aborted"; Gap: "gap"; Forbidden: "forbidden" }>;

export interface AbortResult {
  outcome: AbortOutcome;
}

export type Addressing = (typeof Addressing)[keyof typeof Addressing];
export declare const Addressing: Readonly<{ Content: "content"; Name: "name" }>;

export type AppendOutcome = (typeof AppendOutcome)[keyof typeof AppendOutcome];
export declare const AppendOutcome: Readonly<{ Accepted: "accepted"; Gap: "gap"; Forbidden: "forbidden"; Invalid: "invalid"; OutOfOrder: "out_of_order"; TooLarge: "too_large"; Unavailable: "unavailable" }>;

// For accepted, out_of_order and too_large, received is the next offset the
// service accepts. Other outcomes carry zero.
export interface AppendResult {
  outcome: AppendOutcome;
  received: bigint;
}

export type Attestation = (typeof Attestation)[keyof typeof Attestation];
export declare const Attestation: Readonly<{ Declared: "declared"; Observed: "observed"; Verified: "verified" }>;

// The index entry that proves an observed hold: index is the opaque locator of
// the program's own index (a manifest file, a registry, a configuration), key
// is the entry inside it in the program's own words, role is the program's role
// word for the target inside that entry (Lemonade main, mmproj, draft,
// npu_cache). Verify re-reads this. Holds sharing holder, index and key are one
// grouping in the holder's terms. Absent on declared holds, whose basis is the
// retained request identity.
export interface Basis {
  index: string;
  key: string;
  role: string;
}

export type BeginOutcome = (typeof BeginOutcome)[keyof typeof BeginOutcome];
export declare const BeginOutcome: Readonly<{ Started: "started"; Committed: "committed"; Present: "present"; Forbidden: "forbidden"; Invalid: "invalid"; Conflict: "conflict"; TooLarge: "too_large"; Busy: "busy"; Unsupported: "unsupported"; Unavailable: "unavailable"; Exhausted: "exhausted" }>;

// upload present exactly for started. stored present exactly for committed and
// present. limit is the provider's maximum declared size for evaluated
// outcomes, and zero for forbidden, invalid and unavailable.
export interface BeginResult {
  outcome: BeginOutcome;
  upload: Upload | null;
  stored: Stored | null;
  limit: bigint;
}

// One observed change in provider journal order. Sequence increases within one
// provider epoch. Digest is a canonical sha256 naming key, not verified
// content. Size is observed; zero means unknown. A notice grants no access.
export interface Change {
  sequence: bigint;
  kind: ChangeKind;
  digest: string;
  size: bigint;
}

export type ChangeKind = (typeof ChangeKind)[keyof typeof ChangeKind];
export declare const ChangeKind: Readonly<{ Added: "added"; Removed: "removed" }>;

// page carries at most max_changes entries the caller may read and a next
// cursor. next advances past every entry examined, including entries the caller
// may not read, which are omitted without a count. at_end means the journal end
// was reached during this call. Refusals carry no changes, an unchanged cursor
// and at_end false. gap requires restarting from List.
export interface ChangePage {
  outcome: ChangePageOutcome;
  changes: Change[];
  next: string;
  atEnd: boolean;
}

export type ChangePageOutcome = (typeof ChangePageOutcome)[keyof typeof ChangePageOutcome];
export declare const ChangePageOutcome: Readonly<{ Page: "page"; Gap: "gap"; Forbidden: "forbidden"; Invalid: "invalid"; Unavailable: "unavailable" }>;

// Offset equals requested offset; total equals issued resource size. Length at
// most max_bytes and offset+length at most total. eof iff offset+length equals
// total. Non-EOF data is nonempty. Error/absence never means EOF.
export interface Chunk {
  offset: bigint;
  total: bigint;
  data: Uint8Array;
  eof: boolean;
}

export type CloseOutcome = (typeof CloseOutcome)[keyof typeof CloseOutcome];
export declare const CloseOutcome: Readonly<{ Closed: "closed"; Gap: "gap"; Forbidden: "forbidden" }>;

export interface CloseResult {
  outcome: CloseOutcome;
}

export type CommitOutcome = (typeof CommitOutcome)[keyof typeof CommitOutcome];
export declare const CommitOutcome: Readonly<{ Committed: "committed"; Gap: "gap"; Forbidden: "forbidden"; Incomplete: "incomplete"; Mismatch: "mismatch"; Unavailable: "unavailable" }>;

// stored present exactly for committed with hashed evidence. For incomplete,
// received is the next accepted offset. Other outcomes carry zero.
export interface CommitResult {
  outcome: CommitOutcome;
  stored: Stored | null;
  received: bigint;
}

/** Bounded authorized observation of objects a content store gains or loses. The provider journal retains a bounded number of recent changes per lifetime with no per-subscriber queue; a subscriber that falls behind receives gap and rebuilds from List. Service-mediated commits are journaled when they publish. External additions and deletions are journaled when the provider's optional listing capability is polled; changes that cancel out between polls are not reported. removed currently reports only external deletions, because the service has no delete operation. A provider restart starts a new epoch. */
export declare class ContentChangesClient {
  constructor(transport: FrameTransport);
  /** Empty cursor starts at the current journal end. Cursors are at most 256 bytes and bind provider epoch and sequence. A cursor from another epoch or older than the retained journal returns gap. max_changes is 1..256; wait_ms is 0..30000 and waits at the current end for an append, then rereads once. Observe authorization is checked on every call and rechecked after a wait; each entry is filtered through the read policy for its digest. A read decision outage returns unavailable without advancing. Bounded waiter exhaustion returns unavailable. */
  observe(cursor: string, maxChanges: bigint, waitMs: bigint): Promise<ChangePage>;
  /** Empty continuation freezes a new snapshot of the provider's known objects and its change cursor. limit is 1..256. Continuations are at most 256 bytes and name a retained snapshot; an unknown, expired or restarted snapshot returns gap. At most 8 snapshots are retained, each for 30 idle seconds; exhaustion returns unavailable. Observe authorization and per-object read filtering apply as for Observe. */
  list(continuation: string, limit: bigint): Promise<ListingPage>;
}

export declare const ContentChangesService: Readonly<{ wireName: "abstraction.storage/content-changes@1"; Client: typeof ContentChangesClient }>;

/** Read-only bounded access through configured native Store+Local adapters. Naming lookup is unverified; unsupported providers refuse. Writes use the separate content-writer profile. Callbacks are trusted provider code required to honor bounded execution/context. */
export declare class ContentReaderClient {
  constructor(transport: FrameTransport);
  /** Canonical sha256: plus 64 lowercase hexadecimal digits. Explicit content policy required; same-account identity alone grants no content permission. At most 32 resources globally and 8 per scope; 30 seconds idle expires. */
  open(digest: string): Promise<OpenResult>;
  /** offset>=0; max_bytes is 1..65536. Authority rechecked before bytes. Unknown/expired/closed/restarted resources give gap; another scope's known resource gives forbidden. */
  read(handle: string, offset: bigint, maxBytes: bigint): Promise<ReadResult>;
  /** Release own scoped resource even after content authorization revocation. Provider shutdown closes all owned resources. */
  close(handle: string): Promise<CloseResult>;
}

export declare const ContentReaderService: Readonly<{ wireName: "abstraction.storage/content-reader@1"; Client: typeof ContentReaderClient }>;

export declare class ContentRemoverClient {
  constructor(transport: FrameTransport);
  /** Remove an unheld manifest or object from a Removable store, journaled as removed. Gated by abstraction.storage/content.remove on resource store:<name>. A target only observed holds ever named is removable after a recorded asks answer. A target in a store whose source does not list remove among its capabilities is unsupported. */
  remove(target: string): Promise<RemoveResult>;
}

export declare const ContentRemoverService: Readonly<{ wireName: "abstraction.storage/content-remover@1"; Client: typeof ContentRemoverClient }>;

/** Bounded authorized writes through configured native Store+Local+Writable adapters. Uploads idle for 30 seconds expire and are discarded. Committed request records are retained for 10 minutes within one provider lifetime. Provider shutdown discards staged uploads. */
export declare class ContentWriterClient {
  constructor(transport: FrameTransport);
  /** request is a caller-retained identity of 16..128 characters from A-Z a-z 0-9 _ -, scoped to the receiving account/program. digest is canonical sha256; size is the declared total, 0..limit. Write authorization precedes every lookup and provider effect. The same request with the same digest and size returns its live upload or committed result; different digest or size is conflict. present reports an existing naming match. busy reports another live upload of the same digest. At most 16 uploads globally, 4 per scope and 256 request records. */
  begin(request: string, digest: string, size: bigint): Promise<BeginResult>;
  /** data is 1..65536 bytes at offset equal to received. Authority rechecked before bytes are staged. A different offset stages nothing and returns out_of_order with received. Bytes beyond the declared size stage nothing and return too_large. Unknown/expired/aborted/restarted uploads give gap; another scope's upload gives forbidden. */
  append(handle: string, offset: bigint, data: Uint8Array): Promise<AppendResult>;
  /** Authority rechecked before visibility. Requires received equal to size and the staged bytes to hash to digest; mismatch discards the upload. Visibility changes in one provider commit step; readers observe no partial content. */
  commit(handle: string): Promise<CommitResult>;
  /** Discard own staged upload and its request record, including after write authorization revocation. */
  abort(handle: string): Promise<AbortResult>;
}

export declare const ContentWriterService: Readonly<{ wireName: "abstraction.storage/content-writer@1"; Client: typeof ContentWriterClient }>;

// An index entry naming content the store does not hold, in the program's own
// reference spelling. expected_digest and expected_size are what the index
// itself spells for the absent content (a download manifest's sha256), a claim
// by the holder and never evidence about any present object. A dangling
// reference is a want: the download request that would satisfy it has this
// digest and size.
export interface Dangling {
  holder: Holder;
  basis: Basis;
  reference: string;
  expectedDigest: string;
  expectedSize: bigint;
  observedAt: string;
}

export type DescribeOutcome = (typeof DescribeOutcome)[keyof typeof DescribeOutcome];
export declare const DescribeOutcome: Readonly<{ Described: "described"; Unknown: "unknown"; Forbidden: "forbidden"; Invalid: "invalid"; Unavailable: "unavailable" }>;

// manifest present exactly for described.
export interface DescribeResult {
  outcome: DescribeOutcome;
  manifest: Manifest | null;
}

export declare class DispatchError extends Error {
  constructor(code: string);
  code: string;
}

// One object of a manifest. role is an open catalogue <owner>/<name>; seeds
// weights, weights.config, template, params, license, projector, doc, code,
// dataset. locator names the object in its store and is excluded from the
// manifest id. manifest, present only in a manifest of kind
// abstraction.storage/index@1, references another manifest by id in place of an
// object. digest is empty exactly when evidence is none.
export interface Entry {
  role: string;
  digest: string;
  size: bigint;
  mediaType: string;
  evidence: Evidence;
  locator: string;
  manifest: string;
  annotations: { [key: string]: string };
}

export type Evidence = (typeof Evidence)[keyof typeof Evidence];
export declare const Evidence: Readonly<{ Hashed: "hashed"; Named: "named"; Foreign: "foreign"; None: "none" }>;

// target is a manifest id or a canonical digest. purpose is an open catalogue;
// seeds fetched, installed, pinned, cache. expires is present exactly for
// lease. basis is present exactly for observed and verified holds. A hold
// designates dependence; it grants no access to bytes.
export interface Hold {
  id: string;
  holder: Holder;
  target: string;
  purpose: string;
  lifetime: Lifetime;
  expires: string;
  attestation: Attestation | (string & {});
  observedAt: string;
  basis: Basis | null;
}

export type HoldOutcome = (typeof HoldOutcome)[keyof typeof HoldOutcome];
export declare const HoldOutcome: Readonly<{ Held: "held"; UnknownTarget: "unknown_target"; Conflict: "conflict"; Forbidden: "forbidden"; Invalid: "invalid"; Exhausted: "exhausted"; Unavailable: "unavailable" }>;

// hold present exactly for held.
export interface HoldResult {
  outcome: HoldOutcome;
  hold: Hold | null;
}

// domain is the trust domain in which the holder was bound: empty for this
// service's own local boundary, otherwise the scope this service mapped a
// remote peer's certificate identity to, as the remote job provider maps keys
// to namespaces. A relayed hold keeps the domain of the boundary that
// established it; no domain inherits another's proofs. program is the holder's
// name in the holder vocabulary (ollama, lemonade, comfyui). instance
// distinguishes installations of one program: for declared holds the bound
// peer's normalized executable identity as rights Subject.program spells it;
// for observed holds the source's opaque identity for that installation (a
// Stability Matrix package name, a Pinokio app, an install locator). For
// declared holds account and instance are the receiving boundary's bound peer,
// asserted by the service; for observed holds they are the source's words and
// established_by is the source program the service bound. Never a
// caller-supplied claim.
export interface Holder {
  account: string;
  program: string;
  instance: string;
  establishedBy: string;
  domain: string;
}

/** Declared holds of the bound program. Gated by abstraction.storage/holds.manage, whose contract default permits the bound program on resource self and nothing else. Holds are retained until released, expired, or the program is removed under the uninstall policy; released and expired holds read unknown after audit_retention_ms, readable on an inventory page. */
export declare class HoldsClient {
  constructor(transport: FrameTransport);
  /** request is caller-retained, 16..128 characters from A-Z a-z 0-9 _ -, scoped to the receiving account and program; the same request with the same arguments returns the existing hold, different arguments conflict. Only declared holds are created here; the holder is the bound peer. lease_ms is 1..2592000000 for lease and zero otherwise. At most 4096 holds per program; exhausted otherwise. */
  hold(request: string, target: string, purpose: string, lifetime: Lifetime, leaseMs: bigint): Promise<HoldResult>;
  /** Release an own declared hold. Another program's hold, a released hold past retention and an unknown id are unknown. */
  release(hold: string): Promise<ReleaseResult>;
  /** Extend an own lease by lease_ms from the service's time. An expired lease is expired and is not revived. */
  renew(hold: string, leaseMs: bigint): Promise<RenewResult>;
}

export declare const HoldsService: Readonly<{ wireName: "abstraction.storage/holds@1"; Client: typeof HoldsClient }>;

/** What the machine holds and who depends on it, composed from the service's own tables and every designated source. */
export declare class InventoryClient {
  constructor(transport: FrameTransport);
  /** limit 1..256 combined manifests, stray objects and dangling references per page. Gated by abstraction.storage/inventory.read; each manifest and object is filtered through content.read for its digests. */
  list(continuation: string, limit: bigint): Promise<InventoryPage>;
  /** Every hold on one manifest id or digest, re-observed at call time through each source's Verify: observed holds return as verified or are omitted; declared holds return as declared. Dangling references naming the target's names are included. */
  holders(target: string): Promise<InventoryPage>;
  /** Manifests and objects with no declared hold and no verified observed hold at two observations at least grace_ms apart, oldest first. */
  unheld(continuation: string, limit: bigint): Promise<InventoryPage>;
  /** Manifests and objects carrying this canonical digest with evidence hashed or named, and dangling references whose expected_digest equals it. */
  find(digest: string): Promise<InventoryPage>;
}

export type InventoryOutcome = (typeof InventoryOutcome)[keyof typeof InventoryOutcome];
export declare const InventoryOutcome: Readonly<{ Page: "page"; Gap: "gap"; Forbidden: "forbidden"; Invalid: "invalid"; Unavailable: "unavailable" }>;

// One frozen snapshot across every configured store and designated source;
// cursor is the content-changes cursor at which it was taken. stores is
// complete on the first page and empty afterwards. objects carries only objects
// no manifest entry names. Manifests and objects the caller may not read are
// omitted without a count. Observed holds carry their observation time and
// basis, never a promise of current truth. Refusals carry empty lists, empty
// continuation and cursor, and complete false.
export interface InventoryPage {
  outcome: InventoryOutcome;
  stores: Store[];
  manifests: ManifestHolders[];
  objects: ObjectHolders[];
  dangling: Dangling[];
  continuation: string;
  complete: boolean;
  cursor: string;
  graceMs: bigint;
  auditRetentionMs: bigint;
}

export declare const InventoryService: Readonly<{ wireName: "abstraction.storage/inventory@1"; Client: typeof InventoryClient }>;

/** A provider the runtime reads. The source listens on the shared identity-bound transport and serves only its own account. A call whose peer identity could not be obtained fails with the error code caller_unavailable, and one on a transport that bound no identity with identity_required; a bound peer of another account reads forbidden. The runtime accepts a source only under an abstraction.storage/inventory.provide rule for the bound program and the named stores. Sources never talk to applications. */
export declare class InventorySourceClient {
  constructor(transport: FrameTransport);
  describe(): Promise<SourceDescription>;
  /** Frozen listing of every manifest, stray object and dangling reference the source observes, in store then id order. limit 1..256. No hashing; sizes come from stat and digests only from the program's own index or names. */
  snapshot(continuation: string, limit: bigint): Promise<SourcePage>;
  /** Changes since cursor in journal order; empty cursor starts at the end; gap after restart or an aged cursor. max_changes 1..256; wait_ms 0..30000. */
  observe(cursor: string, maxChanges: bigint, waitMs: bigint): Promise<SourcePage>;
  /** Re-read one target's holders and dangling references now, through their bases. */
  verify(target: string): Promise<SourcePage>;
  /** Only when capabilities lists remove: remove through the owning program's own semantics and update its index. Otherwise unsupported. */
  remove(target: string): Promise<RemoveResult>;
}

export declare const InventorySourceService: Readonly<{ wireName: "abstraction.storage/inventory-source@1"; Client: typeof InventorySourceClient }>;

export type Lifetime = (typeof Lifetime)[keyof typeof Lifetime];
export declare const Lifetime: Readonly<{ UntilReleased: "until_released"; Lease: "lease"; WhilePresent: "while_present" }>;

export interface ListedObject {
  digest: string;
  size: bigint;
}

export type ListingOutcome = (typeof ListingOutcome)[keyof typeof ListingOutcome];
export declare const ListingOutcome: Readonly<{ Page: "page"; Gap: "gap"; Forbidden: "forbidden"; Invalid: "invalid"; Unavailable: "unavailable" }>;

// page carries at most limit objects the caller may read, in digest order, from
// one frozen snapshot. cursor is the change cursor at which that snapshot was
// taken and is identical on every page of it; Observe from it reports every
// later change. complete means the snapshot is exhausted; otherwise
// continuation is nonempty. Objects the caller may not read are omitted without
// a count. Refusals carry no objects, empty continuation and cursor, and
// complete false.
export interface ListingPage {
  outcome: ListingOutcome;
  objects: ListedObject[];
  continuation: string;
  complete: boolean;
  cursor: string;
}

// addressing is content when every entry carries a hashed or named digest: id
// is the sha256 of the canonical encoding of kind, the entries' role, digest,
// size and media_type in declaration order, and descriptor; names, locators,
// annotations and store are excluded, so one manifest is known under several
// names in several stores. addressing is name otherwise: id is the sha256 of
// the canonical encoding of kind, the entries' role, size and media_type,
// descriptor, and names[0], which is the store's own name for it; two
// digest-less manifests differ by what their programs call them. When digests
// later arrive, a content-addressed manifest supersedes the name-addressed one
// and superseded_by records the new id on the old record. Canonical encoding is
// this definition's own encoding with indent 0. kind is an open catalogue;
// seeds abstraction.model/descriptor@1, abstraction.storage/snapshot@1,
// abstraction.storage/object@1, abstraction.storage/index@1. descriptor is a
// string map whose keys the kind defines.
export interface Manifest {
  id: string;
  addressing: Addressing;
  kind: string;
  entries: Entry[];
  names: Name[];
  descriptor: { [key: string]: string };
  store: string;
  supersededBy: string;
}

export interface ManifestHolders {
  manifest: Manifest;
  holds: Hold[];
}

/** Manifests the service knows: published by programs, imported from designated sources, or created by delivery. Gated by abstraction.storage/holds.manage for Publish and by abstraction.storage/inventory.read for Describe of another program's manifest. */
export declare class ManifestsClient {
  constructor(transport: FrameTransport);
  describe(id: string): Promise<DescribeResult>;
  /** Record a content-addressed manifest whose hashed or named entries are all findable, or an index manifest whose referenced manifests are all known. request is a caller-retained identity as in Holds. present reports an identical manifest already recorded. The publishing program receives a declared hold with purpose fetched and a 24-hour lease; it upgrades it through Holds. Name-addressed manifests are published only by designated sources. */
  publish(request: string, manifest: Manifest): Promise<PublishResult>;
}

export declare const ManifestsService: Readonly<{ wireName: "abstraction.storage/manifests@1"; Client: typeof ManifestsClient }>;

// A name a program uses for this manifest, in that program's own vocabulary.
// scheme is an open catalogue; seeds ollama, hf, lmstudio, comfyui, flm, jan,
// oci, stabilitymatrix, pinokio, swarmui.
export interface Name {
  scheme: string;
  name: string;
}

// One stored object, by stat only. locator is opaque provider binding data, as
// storage Ref.locator; applications never treat it as a path or as authority.
// partial marks an interrupted transfer the store spells as such. digest is
// empty exactly when evidence is none.
export interface Object {
  locator: string;
  size: bigint;
  modified: string;
  partial: boolean;
  digest: string;
  evidence: Evidence;
}

// An object no manifest entry names, with any holds on its digest.
export interface ObjectHolders {
  object: Object;
  store: string;
  holds: Hold[];
}

export type OpenOutcome = (typeof OpenOutcome)[keyof typeof OpenOutcome];
export declare const OpenOutcome: Readonly<{ Opened: "opened"; NotFound: "not_found"; Forbidden: "forbidden"; Invalid: "invalid"; Unsupported: "unsupported"; Unavailable: "unavailable"; Exhausted: "exhausted" }>;

// Resource present exactly for opened. Authorization precedes lookup. not_found
// means no known match, not global absence.
export interface OpenResult {
  outcome: OpenOutcome;
  resource: Resource | null;
}

export type Placement = (typeof Placement)[keyof typeof Placement];
export declare const Placement: Readonly<{ Local: "local"; Remote: "remote" }>;

export type PublishOutcome = (typeof PublishOutcome)[keyof typeof PublishOutcome];
export declare const PublishOutcome: Readonly<{ Published: "published"; Present: "present"; Incomplete: "incomplete"; Conflict: "conflict"; Forbidden: "forbidden"; Invalid: "invalid"; Exhausted: "exhausted"; Unavailable: "unavailable" }>;

// manifest present exactly for published and present. missing lists the digests
// of entries the service cannot find; it is empty for every outcome except
// incomplete.
export interface PublishResult {
  outcome: PublishOutcome;
  manifest: Manifest | null;
  missing: string[];
}

export type ReadOutcome = (typeof ReadOutcome)[keyof typeof ReadOutcome];
export declare const ReadOutcome: Readonly<{ Data: "data"; Gap: "gap"; Forbidden: "forbidden"; Invalid: "invalid"; Unavailable: "unavailable"; Changed: "changed" }>;

// Chunk present exactly for data. changed reports observed mutation and
// invalidates resource; discard assembly and explicitly reopen. Mutation
// detection is advisory; verify completed bytes.
export interface ReadResult {
  outcome: ReadOutcome;
  chunk: Chunk | null;
}

export declare class Refusal extends Error {
  constructor(word: string, offset: number);
  word: "malformed" | "bad_string" | "number_spelling" | "wrong_type" | "bad_timestamp" | "depth_exceeded" | "duplicate_key" | "duplicate_field" | "unknown_field" | "missing_field" | "bad_binary" | "bad_enum" | "trailing_bytes";
  offset: number;
}

export type ReleaseOutcome = (typeof ReleaseOutcome)[keyof typeof ReleaseOutcome];
export declare const ReleaseOutcome: Readonly<{ Released: "released"; Unknown: "unknown"; Forbidden: "forbidden"; Invalid: "invalid"; Unavailable: "unavailable" }>;

export interface ReleaseResult {
  outcome: ReleaseOutcome;
}

export type RemoveOutcome = (typeof RemoveOutcome)[keyof typeof RemoveOutcome];
export declare const RemoveOutcome: Readonly<{ Removed: "removed"; NotFound: "not_found"; Held: "held"; Busy: "busy"; Unsupported: "unsupported"; Forbidden: "forbidden"; Invalid: "invalid"; Unavailable: "unavailable" }>;

// held carries the holders whose declared or verified holds prevented removal;
// other outcomes carry none.
export interface RemoveResult {
  outcome: RemoveOutcome;
  holders: Holder[];
}

export type RenewOutcome = (typeof RenewOutcome)[keyof typeof RenewOutcome];
export declare const RenewOutcome: Readonly<{ Renewed: "renewed"; Unknown: "unknown"; Expired: "expired"; Forbidden: "forbidden"; Invalid: "invalid"; Unavailable: "unavailable" }>;

// hold present exactly for renewed.
export interface RenewResult {
  outcome: RenewOutcome;
  hold: Hold | null;
}

// Opaque resource bound to receiving account and observed program and provider
// lifetime. Digest is the requested canonical sha256 naming key, not a verified
// hash. Size is observed and nonnegative. Verification is always unverified;
// consumer verifies assembled bytes. No private path or immutable-snapshot
// claim.
export interface Resource {
  handle: string;
  digest: string;
  size: bigint;
  verification: Verification;
}

export declare class ServiceError extends Error {
  constructor(code: string, message?: string);
  code: string;
}

export type ServiceErrorCode = (typeof ServiceErrorCode)[keyof typeof ServiceErrorCode];
export declare const ServiceErrorCode: Readonly<{ HandlerError: "handler_error"; InvalidResult: "invalid_result"; UnknownVersion: "unknown_version"; UnknownService: "unknown_service"; UnknownMethod: "unknown_method"; WrongMode: "wrong_mode"; CallerUnavailable: "caller_unavailable"; IdentityRequired: "identity_required" }>;

// target is a manifest id, an object locator or a store name. hold present
// exactly for held and released; store present exactly for store_changed.
export interface SourceChange {
  sequence: bigint;
  kind: SourceChangeKind;
  target: string;
  hold: Hold | null;
  store: Store | null;
}

export type SourceChangeKind = (typeof SourceChangeKind)[keyof typeof SourceChangeKind];
export declare const SourceChangeKind: Readonly<{ Added: "added"; Removed: "removed"; Held: "held"; Released: "released"; StoreChanged: "store_changed" }>;

// Refusals carry an empty name and empty lists. capabilities is an open list;
// seeds snapshot, observe, verify, remove. stores carries every store the
// source's discovery rules produced, present or not, with discovery errors.
export interface SourceDescription {
  outcome: SourceDescriptionOutcome;
  name: string;
  stores: Store[];
  schemes: string[];
  capabilities: string[];
}

export type SourceDescriptionOutcome = (typeof SourceDescriptionOutcome)[keyof typeof SourceDescriptionOutcome];
export declare const SourceDescriptionOutcome: Readonly<{ Described: "described"; Forbidden: "forbidden"; Invalid: "invalid"; Unavailable: "unavailable" }>;

// Snapshot pages carry stores on the first page, then manifests, stray objects
// and dangling references, and an empty changes list; Observe pages carry
// changes only. Every hold a source reports has attestation observed and a
// basis; the runtime rewrites established_by from the bound source program and
// refuses any other value. A store's errors travel on its Store record; a page
// never fails for one store's error.
export interface SourcePage {
  outcome: SourcePageOutcome;
  stores: Store[];
  manifests: ManifestHolders[];
  objects: ObjectHolders[];
  dangling: Dangling[];
  changes: SourceChange[];
  continuation: string;
  complete: boolean;
  cursor: string;
}

export type SourcePageOutcome = (typeof SourcePageOutcome)[keyof typeof SourcePageOutcome];
export declare const SourcePageOutcome: Readonly<{ Page: "page"; Gap: "gap"; Forbidden: "forbidden"; Invalid: "invalid"; Unavailable: "unavailable" }>;

// placement is local when the store is read by a source bound on this service's
// own boundary, and remote when its records arrive from a remote service over
// the service-owned authenticated transport; domain is that remote service's
// mapped scope, empty for local. A remote store's locators are opaque here, and
// a shared-filesystem view of another machine's store is never a store. One
// store a source reads. locator is the store's opaque provider binding. rule
// says how the store was found, in the source's own words (a default location,
// an environment variable, a program's configuration, the operator). present
// false means the discovery rule named a store that does not exist; present
// true with no objects is an empty store. A source with no store for a program
// reports nothing for it.
export interface Store {
  name: string;
  program: string;
  locator: string;
  rule: string;
  present: boolean;
  errors: StoreError[];
  placement: Placement;
  domain: string;
}

// One failure inside one store. A store with errors still reports everything
// else it read. kind is display-grade; other carries an unlisted cause.
export interface StoreError {
  kind: StoreErrorKind | (string & {});
  locator: string;
  detail: string;
}

export type StoreErrorKind = (typeof StoreErrorKind)[keyof typeof StoreErrorKind];
export declare const StoreErrorKind: Readonly<{ Other: "other"; MalformedIndex: "malformed_index"; UnreadableIndex: "unreadable_index"; UnreadableTree: "unreadable_tree"; UnreadableConfiguration: "unreadable_configuration" }>;

// hashed: the service hashed every byte it accepted into staging, the hash
// equals digest, and the provider committed that staged object. named: an
// existing provider naming match was found without hashing; size zero means
// unknown.
export interface Stored {
  digest: string;
  size: bigint;
  evidence: Evidence;
}

// Opaque staged upload bound to the receiving account/program scope and
// provider lifetime. Size is the declared total; received counts bytes accepted
// in order. Staged bytes are never findable or readable.
export interface Upload {
  handle: string;
  digest: string;
  size: bigint;
  received: bigint;
}

export type Verification = (typeof Verification)[keyof typeof Verification];
export declare const Verification: Readonly<{ Unverified: "unverified" }>;

export declare function decode(data: Uint8Array): OpenResult;

export declare function decodeAbortResult(data: Uint8Array): AbortResult;

export declare function decodeAppendResult(data: Uint8Array): AppendResult;

export declare function decodeBasis(data: Uint8Array): Basis;

export declare function decodeBeginResult(data: Uint8Array): BeginResult;

export declare function decodeChange(data: Uint8Array): Change;

export declare function decodeChangePage(data: Uint8Array): ChangePage;

export declare function decodeChunk(data: Uint8Array): Chunk;

export declare function decodeCloseResult(data: Uint8Array): CloseResult;

export declare function decodeCommitResult(data: Uint8Array): CommitResult;

export declare function decodeDangling(data: Uint8Array): Dangling;

export declare function decodeDescribeResult(data: Uint8Array): DescribeResult;

export declare function decodeEntry(data: Uint8Array): Entry;

export declare function decodeHold(data: Uint8Array): Hold;

export declare function decodeHoldResult(data: Uint8Array): HoldResult;

export declare function decodeHolder(data: Uint8Array): Holder;

export declare function decodeInventoryPage(data: Uint8Array): InventoryPage;

export declare function decodeListedObject(data: Uint8Array): ListedObject;

export declare function decodeListingPage(data: Uint8Array): ListingPage;

export declare function decodeManifest(data: Uint8Array): Manifest;

export declare function decodeManifestHolders(data: Uint8Array): ManifestHolders;

export declare function decodeName(data: Uint8Array): Name;

export declare function decodeObject(data: Uint8Array): Object;

export declare function decodeObjectHolders(data: Uint8Array): ObjectHolders;

export declare function decodeOpenResult(data: Uint8Array): OpenResult;

export declare function decodePublishResult(data: Uint8Array): PublishResult;

export declare function decodeReadResult(data: Uint8Array): ReadResult;

export declare function decodeReleaseResult(data: Uint8Array): ReleaseResult;

export declare function decodeRemoveResult(data: Uint8Array): RemoveResult;

export declare function decodeRenewResult(data: Uint8Array): RenewResult;

export declare function decodeResource(data: Uint8Array): Resource;

export declare function decodeSourceChange(data: Uint8Array): SourceChange;

export declare function decodeSourceDescription(data: Uint8Array): SourceDescription;

export declare function decodeSourcePage(data: Uint8Array): SourcePage;

export declare function decodeStore(data: Uint8Array): Store;

export declare function decodeStoreError(data: Uint8Array): StoreError;

export declare function decodeStored(data: Uint8Array): Stored;

export declare function decodeUpload(data: Uint8Array): Upload;

export declare function encode(v: OpenResult): Uint8Array;

export declare function encodeAbortResult(v: AbortResult): Uint8Array;

export declare function encodeAppendResult(v: AppendResult): Uint8Array;

export declare function encodeBasis(v: Basis): Uint8Array;

export declare function encodeBeginResult(v: BeginResult): Uint8Array;

export declare function encodeChange(v: Change): Uint8Array;

export declare function encodeChangePage(v: ChangePage): Uint8Array;

export declare function encodeChunk(v: Chunk): Uint8Array;

export declare function encodeCloseResult(v: CloseResult): Uint8Array;

export declare function encodeCommitResult(v: CommitResult): Uint8Array;

export declare function encodeDangling(v: Dangling): Uint8Array;

export declare function encodeDescribeResult(v: DescribeResult): Uint8Array;

export declare function encodeEntry(v: Entry): Uint8Array;

export declare function encodeHold(v: Hold): Uint8Array;

export declare function encodeHoldResult(v: HoldResult): Uint8Array;

export declare function encodeHolder(v: Holder): Uint8Array;

export declare function encodeInventoryPage(v: InventoryPage): Uint8Array;

export declare function encodeListedObject(v: ListedObject): Uint8Array;

export declare function encodeListingPage(v: ListingPage): Uint8Array;

export declare function encodeManifest(v: Manifest): Uint8Array;

export declare function encodeManifestHolders(v: ManifestHolders): Uint8Array;

export declare function encodeName(v: Name): Uint8Array;

export declare function encodeObject(v: Object): Uint8Array;

export declare function encodeObjectHolders(v: ObjectHolders): Uint8Array;

export declare function encodeOpenResult(v: OpenResult): Uint8Array;

export declare function encodePublishResult(v: PublishResult): Uint8Array;

export declare function encodeReadResult(v: ReadResult): Uint8Array;

export declare function encodeReleaseResult(v: ReleaseResult): Uint8Array;

export declare function encodeRemoveResult(v: RemoveResult): Uint8Array;

export declare function encodeRenewResult(v: RenewResult): Uint8Array;

export declare function encodeResource(v: Resource): Uint8Array;

export declare function encodeSourceChange(v: SourceChange): Uint8Array;

export declare function encodeSourceDescription(v: SourceDescription): Uint8Array;

export declare function encodeSourcePage(v: SourcePage): Uint8Array;

export declare function encodeStore(v: Store): Uint8Array;

export declare function encodeStoreError(v: StoreError): Uint8Array;

export declare function encodeStored(v: Stored): Uint8Array;

export declare function encodeUpload(v: Upload): Uint8Array;

export declare const inventorySourceErrorCodes: readonly ["caller_unavailable", "identity_required"];

export declare function newAbortResult(): AbortResult;

export declare function newAppendResult(): AppendResult;

export declare function newBasis(): Basis;

export declare function newBeginResult(): BeginResult;

export declare function newChange(): Change;

export declare function newChangePage(): ChangePage;

export declare function newChunk(): Chunk;

export declare function newCloseResult(): CloseResult;

export declare function newCommitResult(): CommitResult;

export declare function newDangling(): Dangling;

export declare function newDescribeResult(): DescribeResult;

export declare function newEntry(): Entry;

export declare function newHold(): Hold;

export declare function newHoldResult(): HoldResult;

export declare function newHolder(): Holder;

export declare function newInventoryPage(): InventoryPage;

export declare function newListedObject(): ListedObject;

export declare function newListingPage(): ListingPage;

export declare function newManifest(): Manifest;

export declare function newManifestHolders(): ManifestHolders;

export declare function newName(): Name;

export declare function newObject(): Object;

export declare function newObjectHolders(): ObjectHolders;

export declare function newOpenResult(): OpenResult;

export declare function newPublishResult(): PublishResult;

export declare function newReadResult(): ReadResult;

export declare function newReleaseResult(): ReleaseResult;

export declare function newRemoveResult(): RemoveResult;

export declare function newRenewResult(): RenewResult;

export declare function newResource(): Resource;

export declare function newSourceChange(): SourceChange;

export declare function newSourceDescription(): SourceDescription;

export declare function newSourcePage(): SourcePage;

export declare function newStore(): Store;

export declare function newStoreError(): StoreError;

export declare function newStored(): Stored;

export declare function newUpload(): Upload;

export {};
