// Code generated by abstraction-idl from abstraction-storage/content.thrift. DO NOT EDIT.

const HEX = "0123456789abcdef";
const ENC = new TextEncoder();
const SHORT = { 0x22: '\\"', 0x5c: "\\\\", 0x08: "\\b", 0x0c: "\\f", 0x0a: "\\n", 0x0d: "\\r", 0x09: "\\t" };

export class Out {
  constructor() { this.b = []; }
  byte(c) { this.b.push(c); }
  ascii(s) { for (let i = 0; i < s.length; i++) this.b.push(s.charCodeAt(i)); }
  bytes() { return Uint8Array.from(this.b); }
}

function escByte(out, c) {
  const short = SHORT[c];
  if (short !== undefined) out.ascii(short);
  else if (c < 0x20) out.ascii("\\u00" + HEX[c >> 4] + HEX[c & 0xf]);
  else out.byte(c);
}

// Every integer the definition calls i64 is a BigInt here, because Number
// rounds above 2^53 and two values in the conformance record are i64 extremes.
export function num(out, n) { out.ascii(BigInt(n).toString()); }

export function pad(out, depth) { for (let i = 0; i < depth * 2; i++) out.byte(0x20); }

export function strs(out, v, depth) {
  if (v.length === 0) { out.ascii("[]"); return; }
  out.ascii("[\n");
  for (let i = 0; i < v.length; i++) {
    pad(out, depth + 1);
    esc(out, v[i]);
    if (i + 1 < v.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x5d);
}

const isWs = (c) => c === 0x20 || c === 0x09 || c === 0x0a || c === 0x0d;

export function raw(out, s, depth) {
  const b = typeof s === "string" ? ENC.encode(s) : s;
  let i = 0;
  while (i < b.length) {
    const c = b[i];
    if (isWs(c)) { i++; continue; }
    if (c === 0x22) {
      let j = i + 1;
      while (j < b.length) {
        if (b[j] === 0x5c) { j += 2; continue; }
        if (b[j] === 0x22) { j++; break; }
        j++;
      }
      for (let k = i; k < j; k++) out.byte(b[k]);
      i = j;
    } else if (c === 0x7b || c === 0x5b) {
      out.byte(c);
      i++;
      let j = i;
      while (j < b.length && isWs(b[j])) j++;
      if (j < b.length && (b[j] === 0x7d || b[j] === 0x5d)) { out.byte(b[j]); i = j + 1; }
      else { depth++; out.byte(0x0a); pad(out, depth); }
    } else if (c === 0x7d || c === 0x5d) {
      depth--;
      out.byte(0x0a);
      pad(out, depth);
      out.byte(c);
      i++;
    } else if (c === 0x2c) {
      out.ascii(",\n");
      pad(out, depth);
      i++;
    } else if (c === 0x3a) {
      out.ascii(": ");
      i++;
    } else {
      out.byte(c);
      i++;
    }
  }
}

// A JavaScript string sorts by UTF-16 code unit, which puts U+1D11E before
// U+FFFD where every other target puts it after. The definition declares UTF-8
// byte order, so the comparison is done on the encoded bytes.
function byteLess(a, b) {
  const x = ENC.encode(a), y = ENC.encode(b);
  const n = Math.min(x.length, y.length);
  for (let i = 0; i < n; i++) if (x[i] !== y[i]) return x[i] - y[i];
  return x.length - y.length;
}

export function rawmap(out, m, depth) {
  const keys = Object.keys(m).sort(byteLess);
  if (keys.length === 0) { out.ascii("{}"); return; }
  out.ascii("{\n");
  for (let i = 0; i < keys.length; i++) {
    pad(out, depth + 1);
    esc(out, keys[i]);
    out.ascii(": ");
    raw(out, m[keys[i]], depth + 1);
    if (i + 1 < keys.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x7d);
}

export function esc(out, s) {
  out.byte(0x22);
  for (const c of ENC.encode(s)) escByte(out, c);
  out.byte(0x22);
}

function binaryPresent(value) {
  if (!(value instanceof Uint8Array)) throw new Refusal("wrong_type", 0);
  return value.length !== 0;
}
function encodeBinary(value) {
  binaryPresent(value);
  const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  const out = [];
  for (let i = 0; i < value.length; i += 3) {
    const left = value.length - i;
    const v = (value[i] << 16) | ((left > 1 ? value[i+1] : 0) << 8) | (left > 2 ? value[i+2] : 0);
    out.push(alphabet[(v >>> 18) & 63], alphabet[(v >>> 12) & 63], left > 1 ? alphabet[(v >>> 6) & 63] : "=", left > 2 ? alphabet[v & 63] : "=");
  }
  return out.join("");
}
function readBinary(r) {
  const text = r.string();
  const bad = () => { throw r.refuse("bad_binary"); };
  if (text.length % 4 !== 0) bad();
  const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  const out = new Uint8Array(text.length / 4 * 3);
  let size = 0;
  for (let i = 0; i < text.length; i += 4) {
    let v = 0, pad = 0;
    for (let j = 0; j < 4; j++) {
      const c = text[i+j]; let digit = 0;
      if (c === "=") { if (j < 2 || i+4 !== text.length) bad(); pad++; }
      else { if (pad !== 0) bad(); digit = alphabet.indexOf(c); if (digit < 0) bad(); }
      v = (v << 6) | digit;
    }
    out[size++] = (v >>> 16) & 255;
    if (pad < 2) out[size++] = (v >>> 8) & 255;
    if (pad < 1) out[size++] = v & 255;
  }
  const result = out.slice(0, size);
  if (encodeBinary(result) !== text) bad();
  return result;
}

export function encList(out, v, depth, enc) {
  if (v.length === 0) { out.ascii("[]"); return; }
  out.ascii("[\n");
  for (let i = 0; i < v.length; i++) {
    pad(out, depth + 1);
    enc(out, v[i], depth + 1);
    if (i + 1 < v.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x5d);
}

export const VerificationNames = ["unverified"];
export const VerificationUnknown = "refuse";

export const OpenOutcomeNames = ["opened", "not_found", "forbidden", "invalid", "unsupported", "unavailable", "exhausted"];
export const OpenOutcomeUnknown = "refuse";

export const ReadOutcomeNames = ["data", "gap", "forbidden", "invalid", "unavailable", "changed"];
export const ReadOutcomeUnknown = "refuse";

export const CloseOutcomeNames = ["closed", "gap", "forbidden"];
export const CloseOutcomeUnknown = "refuse";

export const BeginOutcomeNames = ["started", "committed", "present", "forbidden", "invalid", "conflict", "too_large", "busy", "unsupported", "unavailable", "exhausted"];
export const BeginOutcomeUnknown = "refuse";

export const AppendOutcomeNames = ["accepted", "gap", "forbidden", "invalid", "out_of_order", "too_large", "unavailable"];
export const AppendOutcomeUnknown = "refuse";

export const CommitOutcomeNames = ["committed", "gap", "forbidden", "incomplete", "mismatch", "unavailable"];
export const CommitOutcomeUnknown = "refuse";

export const AbortOutcomeNames = ["aborted", "gap", "forbidden"];
export const AbortOutcomeUnknown = "refuse";

export const EvidenceNames = ["hashed", "named"];
export const EvidenceUnknown = "refuse";

export const ChangeKindNames = ["added", "removed"];
export const ChangeKindUnknown = "refuse";

export const ChangePageOutcomeNames = ["page", "gap", "forbidden", "invalid", "unavailable"];
export const ChangePageOutcomeUnknown = "refuse";

export const ListingOutcomeNames = ["page", "gap", "forbidden", "invalid", "unavailable"];
export const ListingOutcomeUnknown = "refuse";

export function enc_resource(out, v, depth) {
    if (typeof v.verification !== "string") throw new Refusal("wrong_type",0);
    if (v.verification !== "unverified") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "handle");
  out.ascii(": ");
  esc(out, v.handle);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "digest");
  out.ascii(": ");
  esc(out, v.digest);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "size");
  out.ascii(": ");
  num(out, v.size);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "verification");
  out.ascii(": ");
  esc(out, v.verification);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_openresult(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "opened" && v.outcome !== "not_found" && v.outcome !== "forbidden" && v.outcome !== "invalid" && v.outcome !== "unsupported" && v.outcome !== "unavailable" && v.outcome !== "exhausted") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  if (v.resource !== undefined && v.resource !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "resource");
    out.ascii(": ");
    enc_resource(out, v.resource, depth + 1);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_chunk(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "offset");
  out.ascii(": ");
  num(out, v.offset);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "total");
  out.ascii(": ");
  num(out, v.total);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "data");
  out.ascii(": ");
  esc(out, encodeBinary(v.data));
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "eof");
  out.ascii(": ");
  out.ascii(v.eof ? "true" : "false");
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_readresult(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "data" && v.outcome !== "gap" && v.outcome !== "forbidden" && v.outcome !== "invalid" && v.outcome !== "unavailable" && v.outcome !== "changed") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  if (v.chunk !== undefined && v.chunk !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "chunk");
    out.ascii(": ");
    enc_chunk(out, v.chunk, depth + 1);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_closeresult(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "closed" && v.outcome !== "gap" && v.outcome !== "forbidden") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_upload(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "handle");
  out.ascii(": ");
  esc(out, v.handle);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "digest");
  out.ascii(": ");
  esc(out, v.digest);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "size");
  out.ascii(": ");
  num(out, v.size);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "received");
  out.ascii(": ");
  num(out, v.received);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_stored(out, v, depth) {
    if (typeof v.evidence !== "string") throw new Refusal("wrong_type",0);
    if (v.evidence !== "hashed" && v.evidence !== "named") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "digest");
  out.ascii(": ");
  esc(out, v.digest);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "size");
  out.ascii(": ");
  num(out, v.size);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "evidence");
  out.ascii(": ");
  esc(out, v.evidence);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_beginresult(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "started" && v.outcome !== "committed" && v.outcome !== "present" && v.outcome !== "forbidden" && v.outcome !== "invalid" && v.outcome !== "conflict" && v.outcome !== "too_large" && v.outcome !== "busy" && v.outcome !== "unsupported" && v.outcome !== "unavailable" && v.outcome !== "exhausted") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  if (v.upload !== undefined && v.upload !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "upload");
    out.ascii(": ");
    enc_upload(out, v.upload, depth + 1);
  }
  if (v.stored !== undefined && v.stored !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "stored");
    out.ascii(": ");
    enc_stored(out, v.stored, depth + 1);
  }
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "limit");
  out.ascii(": ");
  num(out, v.limit);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_appendresult(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "accepted" && v.outcome !== "gap" && v.outcome !== "forbidden" && v.outcome !== "invalid" && v.outcome !== "out_of_order" && v.outcome !== "too_large" && v.outcome !== "unavailable") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "received");
  out.ascii(": ");
  num(out, v.received);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_commitresult(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "committed" && v.outcome !== "gap" && v.outcome !== "forbidden" && v.outcome !== "incomplete" && v.outcome !== "mismatch" && v.outcome !== "unavailable") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  if (v.stored !== undefined && v.stored !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "stored");
    out.ascii(": ");
    enc_stored(out, v.stored, depth + 1);
  }
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "received");
  out.ascii(": ");
  num(out, v.received);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_abortresult(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "aborted" && v.outcome !== "gap" && v.outcome !== "forbidden") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_change(out, v, depth) {
    if (typeof v.kind !== "string") throw new Refusal("wrong_type",0);
    if (v.kind !== "added" && v.kind !== "removed") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "sequence");
  out.ascii(": ");
  num(out, v.sequence);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "kind");
  out.ascii(": ");
  esc(out, v.kind);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "digest");
  out.ascii(": ");
  esc(out, v.digest);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "size");
  out.ascii(": ");
  num(out, v.size);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_changepage(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "page" && v.outcome !== "gap" && v.outcome !== "forbidden" && v.outcome !== "invalid" && v.outcome !== "unavailable") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "changes");
  out.ascii(": ");
  encList(out, v.changes, depth + 1, enc_change);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "next");
  out.ascii(": ");
  esc(out, v.next);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "at_end");
  out.ascii(": ");
  out.ascii(v.at_end ? "true" : "false");
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_listedobject(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "digest");
  out.ascii(": ");
  esc(out, v.digest);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "size");
  out.ascii(": ");
  num(out, v.size);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_listingpage(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "page" && v.outcome !== "gap" && v.outcome !== "forbidden" && v.outcome !== "invalid" && v.outcome !== "unavailable") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "objects");
  out.ascii(": ");
  encList(out, v.objects, depth + 1, enc_listedobject);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "continuation");
  out.ascii(": ");
  esc(out, v.continuation);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "complete");
  out.ascii(": ");
  out.ascii(v.complete ? "true" : "false");
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "cursor");
  out.ascii(": ");
  esc(out, v.cursor);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oacontentreaderopenarguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "digest");
  out.ascii(": ");
  esc(out, v.digest);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oacontentreaderreadarguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "handle");
  out.ascii(": ");
  esc(out, v.handle);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "offset");
  out.ascii(": ");
  num(out, v.offset);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "max_bytes");
  out.ascii(": ");
  num(out, v.max_bytes);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oacontentreaderclosearguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "handle");
  out.ascii(": ");
  esc(out, v.handle);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oacontentwriterbeginarguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "request");
  out.ascii(": ");
  esc(out, v.request);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "digest");
  out.ascii(": ");
  esc(out, v.digest);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "size");
  out.ascii(": ");
  num(out, v.size);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oacontentwriterappendarguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "handle");
  out.ascii(": ");
  esc(out, v.handle);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "offset");
  out.ascii(": ");
  num(out, v.offset);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "data");
  out.ascii(": ");
  esc(out, encodeBinary(v.data));
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oacontentwritercommitarguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "handle");
  out.ascii(": ");
  esc(out, v.handle);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oacontentwriterabortarguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "handle");
  out.ascii(": ");
  esc(out, v.handle);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oacontentchangesobservearguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "cursor");
  out.ascii(": ");
  esc(out, v.cursor);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "max_changes");
  out.ascii(": ");
  num(out, v.max_changes);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "wait_ms");
  out.ascii(": ");
  num(out, v.wait_ms);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oacontentchangeslistarguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "continuation");
  out.ascii(": ");
  esc(out, v.continuation);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "limit");
  out.ascii(": ");
  num(out, v.limit);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaserviceframe(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "version");
  out.ascii(": ");
  num(out, v.version);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "service");
  out.ascii(": ");
  esc(out, v.service);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "method");
  out.ascii(": ");
  esc(out, v.method);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "arguments");
  out.ascii(": ");
  for (const byte of (typeof v.arguments === "string" ? ENC.encode(v.arguments) : v.arguments)) out.byte(byte);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaservicereply(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "version");
  out.ascii(": ");
  num(out, v.version);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "service");
  out.ascii(": ");
  esc(out, v.service);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "method");
  out.ascii(": ");
  esc(out, v.method);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "ok");
  out.ascii(": ");
  out.ascii(v.ok ? "true" : "false");
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "payload");
  out.ascii(": ");
  for (const byte of (typeof v.payload === "string" ? ENC.encode(v.payload) : v.payload)) out.byte(byte);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaserviceerror(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "code");
  out.ascii(": ");
  esc(out, v.code);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "message");
  out.ascii(": ");
  esc(out, v.message);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oacontentreaderopenresult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  enc_openresult(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oacontentreaderreadresult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  enc_readresult(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oacontentreadercloseresult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  enc_closeresult(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oacontentwriterbeginresult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  enc_beginresult(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oacontentwriterappendresult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  enc_appendresult(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oacontentwritercommitresult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  enc_commitresult(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oacontentwriterabortresult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  enc_abortresult(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oacontentchangesobserveresult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  enc_changepage(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oacontentchangeslistresult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  enc_listingpage(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function encode(v) {
  const out = new Out();
  enc_openresult(out, v, 0);
  out.byte(0x0a);
  return out.bytes();
}

// A BOM inside a JSON string is data, not a stream signature.
const DEC = new TextDecoder("utf-8", {ignoreBOM: true});
const DEPTH_LIMIT = 64;
const I64_DIGITS = 19;
const UNESCAPE = { 0x22: 0x22, 0x5c: 0x5c, 0x2f: 0x2f, 0x62: 0x08, 0x66: 0x0c, 0x6e: 0x0a, 0x72: 0x0d, 0x74: 0x09 };

export class Refusal extends Error {
  constructor(word, offset) {
    super("refused: " + word + " at byte " + offset);
    this.name = "Refusal";
    this.word = word;
    this.offset = offset;
  }
}

function appendRune(out, cp) {
  if (cp < 0x80) out.push(cp);
  else if (cp < 0x800) out.push(0xc0 | (cp >> 6), 0x80 | (cp & 0x3f));
  else if (cp < 0x10000) out.push(0xe0 | (cp >> 12), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
  else out.push(0xf0 | (cp >> 18), 0x80 | ((cp >> 12) & 0x3f), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
}

// TextDecoder substitutes U+FFFD for a bad sequence rather than reporting it, so
// the bytes are checked before they are decoded and the refusal says so.
function validUtf8(b) {
  for (let i = 0; i < b.length; ) {
    const c = b[i];
    if (c < 0x80) { i++; continue; }
    let n, cp;
    if (c >> 5 === 0x6) { n = 2; cp = c & 0x1f; }
    else if (c >> 4 === 0xe) { n = 3; cp = c & 0x0f; }
    else if (c >> 3 === 0x1e) { n = 4; cp = c & 0x07; }
    else return false;
    if (i + n > b.length) return false;
    for (let k = 1; k < n; k++) {
      if (b[i + k] >> 6 !== 0x2) return false;
      cp = (cp << 6) | (b[i + k] & 0x3f);
    }
    const lowest = [0, 0, 0x80, 0x800, 0x10000][n];
    if (cp < lowest || cp > 0x10ffff || (cp >= 0xd800 && cp <= 0xdfff)) return false;
    i += n;
  }
  return true;
}

class Reader {
  constructor(buf) { this.buf = buf; this.pos = 0; this.depth = 0; }

  refuse(word) { return new Refusal(word, this.pos); }

  at() { return this.pos < this.buf.length ? this.buf[this.pos] : 0; }

  digit() { const c = this.at(); return c >= 0x30 && c <= 0x39; }

  ws() { while (this.pos < this.buf.length && isWs(this.buf[this.pos])) this.pos++; }

  enter() {
    this.depth++;
    if (this.depth > DEPTH_LIMIT) throw this.refuse("depth_exceeded");
  }

  string() {
    if (this.at() !== 0x22) throw this.refuse("wrong_type");
    this.pos++;
    const out = [];
    for (;;) {
      if (this.pos >= this.buf.length) throw this.refuse("malformed");
      const c = this.buf[this.pos];
      if (c === 0x22) {
        this.pos++;
        const bytes = Uint8Array.from(out);
        if (!validUtf8(bytes)) throw this.refuse("bad_string");
        return DEC.decode(bytes);
      }
      if (c < 0x20) throw this.refuse("bad_string");
      if (c === 0x5c) this.escape(out);
      else { out.push(c); this.pos++; }
    }
  }

  escape(out) {
    this.pos++;
    if (this.pos >= this.buf.length) throw this.refuse("malformed");
    const c = this.buf[this.pos];
    this.pos++;
    const plain = UNESCAPE[c];
    if (plain !== undefined) { out.push(plain); return; }
    if (c !== 0x75) throw this.refuse("bad_string");
    let u = this.hex4();
    if (u >= 0xdc00 && u <= 0xdfff) throw this.refuse("bad_string");
    if (u >= 0xd800 && u <= 0xdbff) {
      if (this.pos + 1 >= this.buf.length || this.buf[this.pos] !== 0x5c || this.buf[this.pos + 1] !== 0x75)
        throw this.refuse("bad_string");
      this.pos += 2;
      const low = this.hex4();
      if (low < 0xdc00 || low > 0xdfff) throw this.refuse("bad_string");
      u = 0x10000 + ((u - 0xd800) << 10) + (low - 0xdc00);
    }
    appendRune(out, u);
  }

  hex4() {
    if (this.pos + 4 > this.buf.length) throw this.refuse("bad_string");
    let u = 0;
    for (let i = 0; i < 4; i++) {
      const c = this.buf[this.pos + i];
      if (c >= 0x30 && c <= 0x39) u = (u << 4) | (c - 0x30);
      else if (c >= 0x61 && c <= 0x66) u = (u << 4) | (c - 0x61 + 10);
      else if (c >= 0x41 && c <= 0x46) u = (u << 4) | (c - 0x41 + 10);
      else throw this.refuse("bad_string");
    }
    this.pos += 4;
    return u;
  }

  integer(low, high) {
    const c = this.at();
    if (c !== 0x2d && (c < 0x30 || c > 0x39)) throw this.refuse("wrong_type");
    const negative = c === 0x2d;
    if (negative) this.pos++;
    if (!this.digit()) throw this.refuse("malformed");
    const start = this.pos;
    if (this.at() === 0x30) this.pos++;
    else while (this.digit()) this.pos++;
    const after = this.at();
    if (after === 0x2e || after === 0x65 || after === 0x45 || this.digit()) throw this.refuse("number_spelling");
    if (this.pos - start > I64_DIGITS) throw this.refuse("number_spelling");
    let n = BigInt(String.fromCharCode(...this.buf.subarray(start, this.pos)));
    if (negative) {
      if (n === 0n) throw this.refuse("number_spelling");
      n = -n;
    }
    if (n < low || n > high) throw this.refuse("number_spelling");
    return n;
  }

  boolean() {
    if (this.at() === 0x74) { this.literal("true"); return true; }
    if (this.at() === 0x66) { this.literal("false"); return false; }
    throw this.refuse("wrong_type");
  }

  literal(word) {
    for (let i = 0; i < word.length; i++)
      if (this.buf[this.pos + i] !== word.charCodeAt(i)) throw this.refuse("malformed");
    this.pos += word.length;
  }

  strList() {
    if (this.at() !== 0x5b) throw this.refuse("wrong_type");
    this.enter();
    this.pos++;
    const out = [];
    this.ws();
    if (this.at() !== 0x5d) {
      for (;;) {
        this.ws();
        out.push(this.string());
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== 0x5d) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
    return out;
  }

  rawMap() {
    if (this.at() !== 0x7b) throw this.refuse("wrong_type");
    this.enter();
    this.pos++;
    const out = Object.create(null);
    this.ws();
    if (this.at() !== 0x7d) {
      for (;;) {
        this.ws();
        if (this.at() !== 0x22) throw this.refuse("malformed");
        const k = this.string();
        if (k in out) throw this.refuse("duplicate_key");
        this.ws();
        if (this.at() !== 0x3a) throw this.refuse("malformed");
        this.pos++;
        this.ws();
        out[k] = this.rawValue();
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== 0x7d) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
    return out;
  }

  rawValue() {
    const start = this.pos;
    this.skipValue();
    return this.buf.subarray(start, this.pos);
  }

  skipValue() {
    const c = this.at();
    if (c === 0x22) this.skipString();
    else if (c === 0x7b || c === 0x5b) this.skipContainer();
    else if (c === 0x74) this.literal("true");
    else if (c === 0x66) this.literal("false");
    else if (c === 0x6e) this.literal("null");
    else if (c === 0x2d || (c >= 0x30 && c <= 0x39)) this.skipNumber();
    else throw this.refuse("malformed");
  }

  // An opaque value is validated and carried, never interpreted. Its syntax is
  // the record's own — the same string reader, so an escape, a control byte or a
  // lone surrogate is judged identically at any depth — and what it is free to
  // spell, it keeps: the bytes between these two offsets are what a writer
  // re-emits. A number is walked, never converted, so a value no host type holds
  // survives the reader that carried it.
  skipString() {
    this.string();
  }

  someDigits() {
    let n = 0;
    while (this.at() >= 0x30 && this.at() <= 0x39) { this.pos++; n++; }
    if (n === 0) throw this.refuse("number_spelling");
  }

  skipNumber() {
    if (this.at() === 0x2d) this.pos++;
    const c = this.at();
    if (c === 0x30) this.pos++;
    else if (c > 0x30 && c <= 0x39) { while (this.at() >= 0x30 && this.at() <= 0x39) this.pos++; }
    else throw this.refuse("number_spelling");
    if (this.at() === 0x2e) { this.pos++; this.someDigits(); }
    if (this.at() === 0x65 || this.at() === 0x45) {
      this.pos++;
      if (this.at() === 0x2b || this.at() === 0x2d) this.pos++;
      this.someDigits();
    }
  }

  skipContainer() {
    const opener = this.at();
    const shut = opener === 0x7b ? 0x7d : 0x5d;
    this.enter();
    this.pos++;
    this.ws();
    const seen = new Set();
    if (this.at() !== shut) {
      for (;;) {
        this.ws();
        if (opener === 0x7b) {
          if (this.at() !== 0x22) throw this.refuse("malformed");
          const k = this.string();
          if (seen.has(k)) throw this.refuse("duplicate_key");
          seen.add(k);
          this.ws();
          if (this.at() !== 0x3a) throw this.refuse("malformed");
          this.pos++;
          this.ws();
        }
        this.skipValue();
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== shut) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
  }
}

function decodeList(r, elem) {
  if (r.at() !== 0x5b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const out = [];
  r.ws();
  if (r.at() !== 0x5d) {
    for (;;) {
      r.ws();
      out.push(elem(r));
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x5d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  return out;
}

// Opaque resource bound to receiving account and observed program and provider
// lifetime. Digest is the requested canonical sha256 naming key, not a verified
// hash. Size is observed and nonnegative. Verification is always unverified;
// consumer verifies assembled bytes. No private path or immutable-snapshot
// claim.
export function newResource() {
  return { handle: "", digest: "", size: 0n, verification: "" };
}

// Resource present exactly for opened. Authorization precedes lookup. not_found
// means no known match, not global absence.
export function newOpenResult() {
  return { outcome: "", resource: null };
}

// Offset equals requested offset; total equals issued resource size. Length at
// most max_bytes and offset+length at most total. eof iff offset+length equals
// total. Non-EOF data is nonempty. Error/absence never means EOF.
export function newChunk() {
  return { offset: 0n, total: 0n, data: new Uint8Array(0), eof: false };
}

// Chunk present exactly for data. changed reports observed mutation and
// invalidates resource; discard assembly and explicitly reopen. Mutation
// detection is advisory; verify completed bytes.
export function newReadResult() {
  return { outcome: "", chunk: null };
}

export function newCloseResult() {
  return { outcome: "" };
}

// Opaque staged upload bound to the receiving account/program scope and
// provider lifetime. Size is the declared total; received counts bytes accepted
// in order. Staged bytes are never findable or readable.
export function newUpload() {
  return { handle: "", digest: "", size: 0n, received: 0n };
}

// hashed: the service hashed every byte it accepted into staging, the hash
// equals digest, and the provider committed that staged object. named: an
// existing provider naming match was found without hashing; size zero means
// unknown.
export function newStored() {
  return { digest: "", size: 0n, evidence: "" };
}

// upload present exactly for started. stored present exactly for committed and
// present. limit is the provider's maximum declared size for evaluated
// outcomes, and zero for forbidden, invalid and unavailable.
export function newBeginResult() {
  return { outcome: "", upload: null, stored: null, limit: 0n };
}

// For accepted, out_of_order and too_large, received is the next offset the
// service accepts. Other outcomes carry zero.
export function newAppendResult() {
  return { outcome: "", received: 0n };
}

// stored present exactly for committed with hashed evidence. For incomplete,
// received is the next accepted offset. Other outcomes carry zero.
export function newCommitResult() {
  return { outcome: "", stored: null, received: 0n };
}

export function newAbortResult() {
  return { outcome: "" };
}

// One observed change in provider journal order. Sequence increases within one
// provider epoch. Digest is a canonical sha256 naming key, not verified
// content. Size is observed; zero means unknown. A notice grants no access.
export function newChange() {
  return { sequence: 0n, kind: "", digest: "", size: 0n };
}

// page carries at most max_changes entries the caller may read and a next
// cursor. next advances past every entry examined, including entries the caller
// may not read, which are omitted without a count. at_end means the journal end
// was reached during this call. Refusals carry no changes, an unchanged cursor
// and at_end false. gap requires restarting from List.
export function newChangePage() {
  return { outcome: "", changes: [], next: "", at_end: false };
}

export function newListedObject() {
  return { digest: "", size: 0n };
}

// page carries at most limit objects the caller may read, in digest order, from
// one frozen snapshot. cursor is the change cursor at which that snapshot was
// taken and is identical on every page of it; Observe from it reports every
// later change. complete means the snapshot is exhausted; otherwise
// continuation is nonempty. Objects the caller may not read are omitted without
// a count. Refusals carry no objects, empty continuation and cursor, and
// complete false.
export function newListingPage() {
  return { outcome: "", objects: [], continuation: "", complete: false, cursor: "" };
}

export function newOAContentReaderOpenArguments() {
  return { digest: "" };
}

export function newOAContentReaderReadArguments() {
  return { handle: "", offset: 0n, max_bytes: 0n };
}

export function newOAContentReaderCloseArguments() {
  return { handle: "" };
}

export function newOAContentWriterBeginArguments() {
  return { request: "", digest: "", size: 0n };
}

export function newOAContentWriterAppendArguments() {
  return { handle: "", offset: 0n, data: new Uint8Array(0) };
}

export function newOAContentWriterCommitArguments() {
  return { handle: "" };
}

export function newOAContentWriterAbortArguments() {
  return { handle: "" };
}

export function newOAContentChangesObserveArguments() {
  return { cursor: "", max_changes: 0n, wait_ms: 0n };
}

export function newOAContentChangesListArguments() {
  return { continuation: "", limit: 0n };
}

export function newOAServiceFrame() {
  return { version: 0, service: "", method: "", arguments: "" };
}

export function newOAServiceReply() {
  return { version: 0, service: "", method: "", ok: false, payload: "" };
}

export function newOAServiceError() {
  return { code: "", message: "" };
}

export function newOAContentReaderOpenResult() {
  return { value: newOpenResult() };
}

export function newOAContentReaderReadResult() {
  return { value: newReadResult() };
}

export function newOAContentReaderCloseResult() {
  return { value: newCloseResult() };
}

export function newOAContentWriterBeginResult() {
  return { value: newBeginResult() };
}

export function newOAContentWriterAppendResult() {
  return { value: newAppendResult() };
}

export function newOAContentWriterCommitResult() {
  return { value: newCommitResult() };
}

export function newOAContentWriterAbortResult() {
  return { value: newAbortResult() };
}

export function newOAContentChangesObserveResult() {
  return { value: newChangePage() };
}

export function newOAContentChangesListResult() {
  return { value: newListingPage() };
}

function decode_resource(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newResource();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "handle") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.handle = r.string();
      } else if (key === "digest") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.digest = r.string();
      } else if (key === "size") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.size = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "verification") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.verification = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
    if (v.verification !== "unverified") { throw r.refuse("bad_enum"); }
  return v;
}

function decode_openresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOpenResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "resource") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.resource = decode_resource(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
    if (v.outcome !== "opened" && v.outcome !== "not_found" && v.outcome !== "forbidden" && v.outcome !== "invalid" && v.outcome !== "unsupported" && v.outcome !== "unavailable" && v.outcome !== "exhausted") { throw r.refuse("bad_enum"); }
  return v;
}

function decode_chunk(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newChunk();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "offset") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.offset = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "total") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.total = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "data") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.data = readBinary(r);
      } else if (key === "eof") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.eof = r.boolean();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
  return v;
}

function decode_readresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newReadResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "chunk") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.chunk = decode_chunk(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
    if (v.outcome !== "data" && v.outcome !== "gap" && v.outcome !== "forbidden" && v.outcome !== "invalid" && v.outcome !== "unavailable" && v.outcome !== "changed") { throw r.refuse("bad_enum"); }
  return v;
}

function decode_closeresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newCloseResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
    if (v.outcome !== "closed" && v.outcome !== "gap" && v.outcome !== "forbidden") { throw r.refuse("bad_enum"); }
  return v;
}

function decode_upload(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newUpload();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "handle") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.handle = r.string();
      } else if (key === "digest") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.digest = r.string();
      } else if (key === "size") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.size = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "received") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.received = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
  return v;
}

function decode_stored(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newStored();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "digest") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.digest = r.string();
      } else if (key === "size") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.size = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "evidence") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.evidence = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 7) >>> 0) !== 7) throw r.refuse("missing_field");
    if (v.evidence !== "hashed" && v.evidence !== "named") { throw r.refuse("bad_enum"); }
  return v;
}

function decode_beginresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newBeginResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "upload") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.upload = decode_upload(r);
      } else if (key === "stored") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.stored = decode_stored(r);
      } else if (key === "limit") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.limit = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 9) >>> 0) !== 9) throw r.refuse("missing_field");
    if (v.outcome !== "started" && v.outcome !== "committed" && v.outcome !== "present" && v.outcome !== "forbidden" && v.outcome !== "invalid" && v.outcome !== "conflict" && v.outcome !== "too_large" && v.outcome !== "busy" && v.outcome !== "unsupported" && v.outcome !== "unavailable" && v.outcome !== "exhausted") { throw r.refuse("bad_enum"); }
  return v;
}

function decode_appendresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newAppendResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "received") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.received = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
    if (v.outcome !== "accepted" && v.outcome !== "gap" && v.outcome !== "forbidden" && v.outcome !== "invalid" && v.outcome !== "out_of_order" && v.outcome !== "too_large" && v.outcome !== "unavailable") { throw r.refuse("bad_enum"); }
  return v;
}

function decode_commitresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newCommitResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "stored") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.stored = decode_stored(r);
      } else if (key === "received") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.received = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 5) >>> 0) !== 5) throw r.refuse("missing_field");
    if (v.outcome !== "committed" && v.outcome !== "gap" && v.outcome !== "forbidden" && v.outcome !== "incomplete" && v.outcome !== "mismatch" && v.outcome !== "unavailable") { throw r.refuse("bad_enum"); }
  return v;
}

function decode_abortresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newAbortResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
    if (v.outcome !== "aborted" && v.outcome !== "gap" && v.outcome !== "forbidden") { throw r.refuse("bad_enum"); }
  return v;
}

function decode_change(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newChange();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "sequence") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.sequence = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "kind") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.kind = r.string();
      } else if (key === "digest") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.digest = r.string();
      } else if (key === "size") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.size = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
    if (v.kind !== "added" && v.kind !== "removed") { throw r.refuse("bad_enum"); }
  return v;
}

function decode_changepage(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newChangePage();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "changes") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.changes = decodeList(r, decode_change);
      } else if (key === "next") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.next = r.string();
      } else if (key === "at_end") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.at_end = r.boolean();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
    if (v.outcome !== "page" && v.outcome !== "gap" && v.outcome !== "forbidden" && v.outcome !== "invalid" && v.outcome !== "unavailable") { throw r.refuse("bad_enum"); }
  return v;
}

function decode_listedobject(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newListedObject();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "digest") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.digest = r.string();
      } else if (key === "size") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.size = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function decode_listingpage(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newListingPage();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "objects") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.objects = decodeList(r, decode_listedobject);
      } else if (key === "continuation") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.continuation = r.string();
      } else if (key === "complete") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.complete = r.boolean();
      } else if (key === "cursor") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.cursor = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 31) >>> 0) !== 31) throw r.refuse("missing_field");
    if (v.outcome !== "page" && v.outcome !== "gap" && v.outcome !== "forbidden" && v.outcome !== "invalid" && v.outcome !== "unavailable") { throw r.refuse("bad_enum"); }
  return v;
}

function decode_oacontentreaderopenarguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAContentReaderOpenArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "digest") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.digest = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oacontentreaderreadarguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAContentReaderReadArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "handle") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.handle = r.string();
      } else if (key === "offset") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.offset = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "max_bytes") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.max_bytes = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 7) >>> 0) !== 7) throw r.refuse("missing_field");
  return v;
}

function decode_oacontentreaderclosearguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAContentReaderCloseArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "handle") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.handle = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oacontentwriterbeginarguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAContentWriterBeginArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "request") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.request = r.string();
      } else if (key === "digest") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.digest = r.string();
      } else if (key === "size") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.size = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 7) >>> 0) !== 7) throw r.refuse("missing_field");
  return v;
}

function decode_oacontentwriterappendarguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAContentWriterAppendArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "handle") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.handle = r.string();
      } else if (key === "offset") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.offset = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "data") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.data = readBinary(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 7) >>> 0) !== 7) throw r.refuse("missing_field");
  return v;
}

function decode_oacontentwritercommitarguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAContentWriterCommitArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "handle") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.handle = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oacontentwriterabortarguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAContentWriterAbortArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "handle") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.handle = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oacontentchangesobservearguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAContentChangesObserveArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "cursor") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.cursor = r.string();
      } else if (key === "max_changes") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.max_changes = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "wait_ms") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.wait_ms = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 7) >>> 0) !== 7) throw r.refuse("missing_field");
  return v;
}

function decode_oacontentchangeslistarguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAContentChangesListArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "continuation") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.continuation = r.string();
      } else if (key === "limit") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.limit = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function decode_oaserviceframe(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceFrame();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "version") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.version = Number(r.integer(-2147483648n, 2147483647n));
      } else if (key === "service") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.service = r.string();
      } else if (key === "method") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.method = r.string();
      } else if (key === "arguments") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.arguments = r.rawValue();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
  return v;
}

function decode_oaservicereply(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceReply();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "version") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.version = Number(r.integer(-2147483648n, 2147483647n));
      } else if (key === "service") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.service = r.string();
      } else if (key === "method") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.method = r.string();
      } else if (key === "ok") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.ok = r.boolean();
      } else if (key === "payload") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.payload = r.rawValue();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 31) >>> 0) !== 31) throw r.refuse("missing_field");
  return v;
}

function decode_oaserviceerror(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceError();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "code") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.code = r.string();
      } else if (key === "message") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.message = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function decode_oacontentreaderopenresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAContentReaderOpenResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = decode_openresult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oacontentreaderreadresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAContentReaderReadResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = decode_readresult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oacontentreadercloseresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAContentReaderCloseResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = decode_closeresult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oacontentwriterbeginresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAContentWriterBeginResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = decode_beginresult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oacontentwriterappendresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAContentWriterAppendResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = decode_appendresult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oacontentwritercommitresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAContentWriterCommitResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = decode_commitresult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oacontentwriterabortresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAContentWriterAbortResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = decode_abortresult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oacontentchangesobserveresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAContentChangesObserveResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = decode_changepage(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oacontentchangeslistresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAContentChangesListResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = decode_listingpage(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

export function decode(data) {
  const r = new Reader(data);
  r.ws();
  const v = decode_openresult(r);
  r.ws();
  if (r.pos < r.buf.length) throw r.refuse("trailing_bytes");
  return v;
}

// refusals is in the order two of them are chosen between.
export const refusals = ["malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_binary", "bad_enum", "trailing_bytes"];

export function refusalRank(word) {
  return refusals.indexOf(word);
}

export class DispatchError extends Error {
  constructor(code) { super(code); this.name = "DispatchError"; this.code = code; }
}
export class ServiceError extends Error {
  constructor(code, message = "") { super(message || code); this.name = "ServiceError"; this.code = code; }
}
function _serviceDecode(decoder, frame, depth) {
  const reader = new Reader(typeof frame === "string" ? ENC.encode(frame) : frame);
  reader.depth = depth; reader.ws();
  const value = decoder(reader); reader.ws();
  if (reader.pos !== reader.buf.length) throw reader.refuse("trailing_bytes");
  return value;
}
function _serviceEncode(encoder, value, depth) {
  const out = new Out(); encoder(out, value, depth); return out.bytes();
}
function _serviceCheck(kind, value, depth = 0) {
  if (depth > DEPTH_LIMIT) throw new Refusal("depth_exceeded", 0);
  let valid = false;
  if (kind === "string") {
    valid = typeof value === "string";
    if (valid) for (const ch of value) {
      const cp = ch.codePointAt(0);
      if (cp >= 0xd800 && cp <= 0xdfff) throw new Refusal("bad_string", 0);
    }
  } else if (kind === "i32") {
    valid = typeof value === "number" && Number.isInteger(value) && value >= -2147483648 && value <= 2147483647;
  } else if (kind === "i64") {
    valid = typeof value === "bigint" && value >= -9223372036854775808n && value <= 9223372036854775807n;
  } else if (kind === "bool") valid = typeof value === "boolean";
  else if (kind === "binary") valid = value instanceof Uint8Array;
  else if (kind === "json") {
    valid = typeof value === "string" || value instanceof Uint8Array;
    if (valid) { const r = new Reader(typeof value === "string" ? ENC.encode(value) : value); r.depth = depth; r.ws(); r.rawValue(); r.ws(); if (r.pos !== r.buf.length) throw r.refuse("trailing_bytes"); }
  } else if (kind.startsWith("list<")) {
    valid = Array.isArray(value);
    if (valid) for (const item of value) _serviceCheck(kind.slice(5,-1), item, depth + 1);
  } else if (kind.startsWith("map<string,")) {
    valid = value !== null && typeof value === "object" && !Array.isArray(value);
    if (valid) for (const [key,item] of Object.entries(value)) { _serviceCheck("string",key,depth+1); _serviceCheck(kind.slice(11,-1),item,depth+1); }
  } else {
    const fields = _serviceRecords[kind];
    valid = fields !== undefined && value !== null && typeof value === "object" && !Array.isArray(value);
    if (valid) for (const [name,type,omit] of fields) {
      if (!Object.hasOwn(value,name)) throw new Refusal("missing_field",0);
      const item = value[name];
      if (omit === "absent" && item === null) continue;
      _serviceCheck(type,item,depth+1);
    }
  }
  if (!valid) throw new Refusal("wrong_type", 0);
}

const _serviceRecords = Object.create(null);
_serviceRecords["Resource"] = [["handle","string","never"],["digest","string","never"],["size","i64","never"],["verification","string","never"],];
_serviceRecords["OpenResult"] = [["outcome","string","never"],["resource","Resource","absent"],];
_serviceRecords["Chunk"] = [["offset","i64","never"],["total","i64","never"],["data","binary","never"],["eof","bool","never"],];
_serviceRecords["ReadResult"] = [["outcome","string","never"],["chunk","Chunk","absent"],];
_serviceRecords["CloseResult"] = [["outcome","string","never"],];
_serviceRecords["Upload"] = [["handle","string","never"],["digest","string","never"],["size","i64","never"],["received","i64","never"],];
_serviceRecords["Stored"] = [["digest","string","never"],["size","i64","never"],["evidence","string","never"],];
_serviceRecords["BeginResult"] = [["outcome","string","never"],["upload","Upload","absent"],["stored","Stored","absent"],["limit","i64","never"],];
_serviceRecords["AppendResult"] = [["outcome","string","never"],["received","i64","never"],];
_serviceRecords["CommitResult"] = [["outcome","string","never"],["stored","Stored","absent"],["received","i64","never"],];
_serviceRecords["AbortResult"] = [["outcome","string","never"],];
_serviceRecords["Change"] = [["sequence","i64","never"],["kind","string","never"],["digest","string","never"],["size","i64","never"],];
_serviceRecords["ChangePage"] = [["outcome","string","never"],["changes","list<Change>","never"],["next","string","never"],["at_end","bool","never"],];
_serviceRecords["ListedObject"] = [["digest","string","never"],["size","i64","never"],];
_serviceRecords["ListingPage"] = [["outcome","string","never"],["objects","list<ListedObject>","never"],["continuation","string","never"],["complete","bool","never"],["cursor","string","never"],];
_serviceRecords["OAContentReaderOpenArguments"] = [["digest","string","never"],];
_serviceRecords["OAContentReaderReadArguments"] = [["handle","string","never"],["offset","i64","never"],["max_bytes","i64","never"],];
_serviceRecords["OAContentReaderCloseArguments"] = [["handle","string","never"],];
_serviceRecords["OAContentWriterBeginArguments"] = [["request","string","never"],["digest","string","never"],["size","i64","never"],];
_serviceRecords["OAContentWriterAppendArguments"] = [["handle","string","never"],["offset","i64","never"],["data","binary","never"],];
_serviceRecords["OAContentWriterCommitArguments"] = [["handle","string","never"],];
_serviceRecords["OAContentWriterAbortArguments"] = [["handle","string","never"],];
_serviceRecords["OAContentChangesObserveArguments"] = [["cursor","string","never"],["max_changes","i64","never"],["wait_ms","i64","never"],];
_serviceRecords["OAContentChangesListArguments"] = [["continuation","string","never"],["limit","i64","never"],];
_serviceRecords["OAServiceFrame"] = [["version","i32","never"],["service","string","never"],["method","string","never"],["arguments","json","never"],];
_serviceRecords["OAServiceReply"] = [["version","i32","never"],["service","string","never"],["method","string","never"],["ok","bool","never"],["payload","json","never"],];
_serviceRecords["OAServiceError"] = [["code","string","never"],["message","string","never"],];
_serviceRecords["OAContentReaderOpenResult"] = [["value","OpenResult","never"],];
_serviceRecords["OAContentReaderReadResult"] = [["value","ReadResult","never"],];
_serviceRecords["OAContentReaderCloseResult"] = [["value","CloseResult","never"],];
_serviceRecords["OAContentWriterBeginResult"] = [["value","BeginResult","never"],];
_serviceRecords["OAContentWriterAppendResult"] = [["value","AppendResult","never"],];
_serviceRecords["OAContentWriterCommitResult"] = [["value","CommitResult","never"],];
_serviceRecords["OAContentWriterAbortResult"] = [["value","AbortResult","never"],];
_serviceRecords["OAContentChangesObserveResult"] = [["value","ChangePage","never"],];
_serviceRecords["OAContentChangesListResult"] = [["value","ListingPage","never"],];

function _serviceRequest(service, method, argumentsBytes) {
  return _serviceEncode(enc_oaserviceframe, {
    version:1, service, method, arguments:new TextDecoder("utf-8",{fatal:true}).decode(argumentsBytes)
  },0);
}

function _serviceResponse(frame, service, method) {
  if (!(frame instanceof Uint8Array)) throw new TypeError("transport frame must be Uint8Array");
  const reply = _serviceDecode(decode_oaservicereply, frame, 0);
  if (reply.version !== 1) throw new DispatchError("unknown_version");
  if (reply.service !== service || reply.method !== method) throw new DispatchError("mismatched_response");
  if (!reply.ok) {
    const error = _serviceDecode(decode_oaserviceerror, reply.payload, 1);
    if (!error.code) throw new DispatchError("invalid_error");
    throw new ServiceError(error.code, error.message);
  }
  return reply.payload;
}

export class ContentReaderClient {
  constructor(transport) { this._transport = transport; }
  async Open(arg0) {
    const args = newOAContentReaderOpenArguments();
    args["digest"] = arg0;
    _serviceCheck("OAContentReaderOpenArguments", args);
    const payload = _serviceEncode(enc_oacontentreaderopenarguments, args, 1);
    _serviceDecode(decode_oacontentreaderopenarguments, payload, 1);
    const request = _serviceRequest("abstraction.storage/content-reader@1", "Open", payload);
    const reply = _serviceResponse(await this._transport.exchangeFrame(request), "abstraction.storage/content-reader@1", "Open");
    const result = _serviceDecode(decode_oacontentreaderopenresult, reply, 1);
    return result.value;
  }
  async Read(arg0,arg1,arg2) {
    const args = newOAContentReaderReadArguments();
    args["handle"] = arg0;
    args["offset"] = arg1;
    args["max_bytes"] = arg2;
    _serviceCheck("OAContentReaderReadArguments", args);
    const payload = _serviceEncode(enc_oacontentreaderreadarguments, args, 1);
    _serviceDecode(decode_oacontentreaderreadarguments, payload, 1);
    const request = _serviceRequest("abstraction.storage/content-reader@1", "Read", payload);
    const reply = _serviceResponse(await this._transport.exchangeFrame(request), "abstraction.storage/content-reader@1", "Read");
    const result = _serviceDecode(decode_oacontentreaderreadresult, reply, 1);
    return result.value;
  }
  async Close(arg0) {
    const args = newOAContentReaderCloseArguments();
    args["handle"] = arg0;
    _serviceCheck("OAContentReaderCloseArguments", args);
    const payload = _serviceEncode(enc_oacontentreaderclosearguments, args, 1);
    _serviceDecode(decode_oacontentreaderclosearguments, payload, 1);
    const request = _serviceRequest("abstraction.storage/content-reader@1", "Close", payload);
    const reply = _serviceResponse(await this._transport.exchangeFrame(request), "abstraction.storage/content-reader@1", "Close");
    const result = _serviceDecode(decode_oacontentreadercloseresult, reply, 1);
    return result.value;
  }
}
export const ContentReaderService = Object.freeze({wireName:"abstraction.storage/content-reader@1",Client:ContentReaderClient});

export class ContentWriterClient {
  constructor(transport) { this._transport = transport; }
  async Begin(arg0,arg1,arg2) {
    const args = newOAContentWriterBeginArguments();
    args["request"] = arg0;
    args["digest"] = arg1;
    args["size"] = arg2;
    _serviceCheck("OAContentWriterBeginArguments", args);
    const payload = _serviceEncode(enc_oacontentwriterbeginarguments, args, 1);
    _serviceDecode(decode_oacontentwriterbeginarguments, payload, 1);
    const request = _serviceRequest("abstraction.storage/content-writer@1", "Begin", payload);
    const reply = _serviceResponse(await this._transport.exchangeFrame(request), "abstraction.storage/content-writer@1", "Begin");
    const result = _serviceDecode(decode_oacontentwriterbeginresult, reply, 1);
    return result.value;
  }
  async Append(arg0,arg1,arg2) {
    const args = newOAContentWriterAppendArguments();
    args["handle"] = arg0;
    args["offset"] = arg1;
    args["data"] = arg2;
    _serviceCheck("OAContentWriterAppendArguments", args);
    const payload = _serviceEncode(enc_oacontentwriterappendarguments, args, 1);
    _serviceDecode(decode_oacontentwriterappendarguments, payload, 1);
    const request = _serviceRequest("abstraction.storage/content-writer@1", "Append", payload);
    const reply = _serviceResponse(await this._transport.exchangeFrame(request), "abstraction.storage/content-writer@1", "Append");
    const result = _serviceDecode(decode_oacontentwriterappendresult, reply, 1);
    return result.value;
  }
  async Commit(arg0) {
    const args = newOAContentWriterCommitArguments();
    args["handle"] = arg0;
    _serviceCheck("OAContentWriterCommitArguments", args);
    const payload = _serviceEncode(enc_oacontentwritercommitarguments, args, 1);
    _serviceDecode(decode_oacontentwritercommitarguments, payload, 1);
    const request = _serviceRequest("abstraction.storage/content-writer@1", "Commit", payload);
    const reply = _serviceResponse(await this._transport.exchangeFrame(request), "abstraction.storage/content-writer@1", "Commit");
    const result = _serviceDecode(decode_oacontentwritercommitresult, reply, 1);
    return result.value;
  }
  async Abort(arg0) {
    const args = newOAContentWriterAbortArguments();
    args["handle"] = arg0;
    _serviceCheck("OAContentWriterAbortArguments", args);
    const payload = _serviceEncode(enc_oacontentwriterabortarguments, args, 1);
    _serviceDecode(decode_oacontentwriterabortarguments, payload, 1);
    const request = _serviceRequest("abstraction.storage/content-writer@1", "Abort", payload);
    const reply = _serviceResponse(await this._transport.exchangeFrame(request), "abstraction.storage/content-writer@1", "Abort");
    const result = _serviceDecode(decode_oacontentwriterabortresult, reply, 1);
    return result.value;
  }
}
export const ContentWriterService = Object.freeze({wireName:"abstraction.storage/content-writer@1",Client:ContentWriterClient});

export class ContentChangesClient {
  constructor(transport) { this._transport = transport; }
  async Observe(arg0,arg1,arg2) {
    const args = newOAContentChangesObserveArguments();
    args["cursor"] = arg0;
    args["max_changes"] = arg1;
    args["wait_ms"] = arg2;
    _serviceCheck("OAContentChangesObserveArguments", args);
    const payload = _serviceEncode(enc_oacontentchangesobservearguments, args, 1);
    _serviceDecode(decode_oacontentchangesobservearguments, payload, 1);
    const request = _serviceRequest("abstraction.storage/content-changes@1", "Observe", payload);
    const reply = _serviceResponse(await this._transport.exchangeFrame(request), "abstraction.storage/content-changes@1", "Observe");
    const result = _serviceDecode(decode_oacontentchangesobserveresult, reply, 1);
    return result.value;
  }
  async List(arg0,arg1) {
    const args = newOAContentChangesListArguments();
    args["continuation"] = arg0;
    args["limit"] = arg1;
    _serviceCheck("OAContentChangesListArguments", args);
    const payload = _serviceEncode(enc_oacontentchangeslistarguments, args, 1);
    _serviceDecode(decode_oacontentchangeslistarguments, payload, 1);
    const request = _serviceRequest("abstraction.storage/content-changes@1", "List", payload);
    const reply = _serviceResponse(await this._transport.exchangeFrame(request), "abstraction.storage/content-changes@1", "List");
    const result = _serviceDecode(decode_oacontentchangeslistresult, reply, 1);
    return result.value;
  }
}
export const ContentChangesService = Object.freeze({wireName:"abstraction.storage/content-changes@1",Client:ContentChangesClient});
