# Code generated by abstraction-idl from abstraction-storage/storage.thrift. DO NOT EDIT.

"""abstraction.storage.api: generated contract types, vocabularies and service clients."""

from ._codec import (
    FAILURE_NAMES,
    FindResult,
    Local,
    Ref,
    Refusal,
    Store,
    Writable,
    decode,
    encode,
)

__all__ = [
    "FAILURE_NAMES",
    "FindResult",
    "Local",
    "Ref",
    "Refusal",
    "Store",
    "Writable",
    "decode",
    "encode",
]

# Report every class and function as a member of this package, so help(),
# tracebacks and pickles name the import an application writes.
for _name in __all__:
    _value = globals()[_name]
    if isinstance(_value, type) or callable(_value):
        _value.__module__ = __name__
del _name, _value
