// Code generated by abstraction-idl from abstraction-storage/lend.thrift. DO NOT EDIT.

package lend

type Raw = string

func escByte(out []byte, c byte) []byte {
	const hex = "0123456789abcdef"
	switch c {
	case '"':
		return append(out, '\\', '"')
	case '\\':
		return append(out, '\\', '\\')
	case 0x08:
		return append(out, '\\', 'b')
	case 0x0c:
		return append(out, '\\', 'f')
	case '\n':
		return append(out, '\\', 'n')
	case '\r':
		return append(out, '\\', 'r')
	case '\t':
		return append(out, '\\', 't')
	}
	if c < 0x20 {
		return append(out, '\\', 'u', '0', '0', hex[c>>4], hex[c&0xF])
	}
	return append(out, c)
}

func num(out []byte, n int64) []byte {
	if n == 0 {
		return append(out, '0')
	}
	var d [24]byte
	p := len(d)
	u := uint64(n)
	if n < 0 {
		u = -uint64(n)
	}
	for u > 0 {
		p--
		d[p] = byte('0' + u%10)
		u /= 10
	}
	if n < 0 {
		out = append(out, '-')
	}
	return append(out, d[p:]...)
}

func pad(out []byte, depth int) []byte {
	for i := 0; i < depth*2; i++ {
		out = append(out, ' ')
	}
	return out
}

func strs(out []byte, v []string, depth int) []byte {
	if len(v) == 0 {
		return append(out, '[', ']')
	}
	out = append(out, '[', '\n')
	for i, s := range v {
		out = pad(out, depth+1)
		out = esc(out, s)
		if i+1 < len(v) {
			out = append(out, ',')
		}
		out = append(out, '\n')
	}
	out = pad(out, depth)
	return append(out, ']')
}

func raw(out []byte, s string, depth int) []byte {
	ws := func(c byte) bool { return c == ' ' || c == '\t' || c == '\n' || c == '\r' }
	for i := 0; i < len(s); {
		c := s[i]
		if ws(c) {
			i++
			continue
		}
		switch c {
		case '"':
			j := i + 1
			for j < len(s) {
				if s[j] == '\\' {
					j += 2
					continue
				}
				if s[j] == '"' {
					j++
					break
				}
				j++
			}
			out = append(out, s[i:j]...)
			i = j
		case '{', '[':
			out = append(out, c)
			i++
			j := i
			for j < len(s) && ws(s[j]) {
				j++
			}
			if j < len(s) && (s[j] == '}' || s[j] == ']') {
				out = append(out, s[j])
				i = j + 1
			} else {
				depth++
				out = append(out, '\n')
				out = pad(out, depth)
			}
		case '}', ']':
			depth--
			out = append(out, '\n')
			out = pad(out, depth)
			out = append(out, c)
			i++
		case ',':
			out = append(out, ',', '\n')
			out = pad(out, depth)
			i++
		case ':':
			out = append(out, ':', ' ')
			i++
		default:
			out = append(out, c)
			i++
		}
	}
	return out
}

func byteLess(a, b string) bool {
	n := len(a)
	if len(b) < n {
		n = len(b)
	}
	for i := 0; i < n; i++ {
		if a[i] != b[i] {
			return a[i] < b[i]
		}
	}
	return len(a) < len(b)
}

func sortedKeys(m map[string]Raw) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	for i := 1; i < len(keys); i++ {
		for j := i; j > 0 && byteLess(keys[j], keys[j-1]); j-- {
			keys[j], keys[j-1] = keys[j-1], keys[j]
		}
	}
	return keys
}

func rawmap(out []byte, m map[string]Raw, depth int) []byte {
	keys := sortedKeys(m)
	if len(keys) == 0 {
		return append(out, '{', '}')
	}
	out = append(out, '{', '\n')
	for i, k := range keys {
		out = pad(out, depth+1)
		out = esc(out, k)
		out = append(out, ':', ' ')
		out = raw(out, m[k], depth+1)
		if i+1 < len(keys) {
			out = append(out, ',')
		}
		out = append(out, '\n')
	}
	out = pad(out, depth)
	return append(out, '}')
}

func esc(out []byte, s string) []byte {
	out = append(out, '"')
	for i := 0; i < len(s); i++ {
		out = escByte(out, s[i])
	}
	return append(out, '"')
}

func encList[T any](out []byte, v []T, depth int, enc func([]byte, *T, int) []byte) []byte {
	if len(v) == 0 {
		return append(out, '[', ']')
	}
	out = append(out, '[', '\n')
	for i := range v {
		out = pad(out, depth+1)
		out = enc(out, &v[i], depth+1)
		if i+1 < len(v) {
			out = append(out, ',')
		}
		out = append(out, '\n')
	}
	out = pad(out, depth)
	return append(out, ']')
}

// Link is a closed vocabulary. Its numeric values are private implementation
// tags; String and ParseLink preserve the exact wire words.
type Link uint32

const (
	LinkSymbolic Link = 1
	LinkHard     Link = 2
	LinkCopy     Link = 3
)

// String returns v's exact wire word, or the empty string for an invalid value.
func (v Link) String() string {
	word, _ := v.WireName()
	return word
}

// WireName returns v's exact wire word and whether v names a member.
func (v Link) WireName() (string, bool) {
	switch v {
	case LinkSymbolic:
		return "symbolic", true
	case LinkHard:
		return "hard", true
	case LinkCopy:
		return "copy", true
	}
	return "", false
}

// ParseLink returns the member named by an exact wire word.
func ParseLink(word string) (Link, bool) {
	switch word {
	case "symbolic":
		return LinkSymbolic, true
	case "hard":
		return LinkHard, true
	case "copy":
		return LinkCopy, true
	}
	return Link(0), false
}

// MarshalText preserves the member's exact wire word for standard text users,
// including JSON object keys. Invalid and zero values are refused.
func (v Link) MarshalText() ([]byte, error) {
	word, ok := v.WireName()
	if !ok {
		return nil, &Refusal{Word: "bad_enum", Offset: 0}
	}
	return []byte(word), nil
}

// UnmarshalText accepts an exact wire word and refuses unknown text.
func (v *Link) UnmarshalText(text []byte) error {
	word, ok := ParseLink(string(text))
	if !ok {
		return &Refusal{Word: "bad_enum", Offset: 0}
	}
	*v = word
	return nil
}

// MarshalJSON keeps closed vocabularies as JSON strings rather than their
// private numeric implementation tags.
func (v Link) MarshalJSON() ([]byte, error) {
	word, ok := v.WireName()
	if !ok {
		return nil, &Refusal{Word: "bad_enum", Offset: 0}
	}
	return esc(nil, word), nil
}

// UnmarshalJSON accepts only an exact JSON string member. Numbers, null and
// unknown strings are refused by the same codec rules as generated records.
func (v *Link) UnmarshalJSON(data []byte) error {
	r := reader{buf: data}
	r.ws()
	word, err := r.str()
	if err != nil {
		return err
	}
	r.ws()
	if r.pos != len(r.buf) {
		return r.refuse("trailing_bytes")
	}
	parsed, ok := ParseLink(word)
	if !ok {
		return r.refuse("bad_enum")
	}
	*v = parsed
	return nil
}

// LinkValues returns every member of Link in declaration order, in a new slice.
func LinkValues() []Link {
	return []Link{LinkSymbolic, LinkHard, LinkCopy}
}

// Known reports whether v is a member of Link.
func (v Link) Known() bool {
	_, ok := v.WireName()
	return ok
}

// LendOutcome is a closed vocabulary. Its numeric values are private implementation
// tags; String and ParseLendOutcome preserve the exact wire words.
type LendOutcome uint32

const (
	LendOutcomeLent              LendOutcome = 1
	LendOutcomeNotPermitted      LendOutcome = 2
	LendOutcomeUnsupportedEngine LendOutcome = 3
	LendOutcomeLinkRefused       LendOutcome = 4
	LendOutcomeAlreadyLent       LendOutcome = 5
	LendOutcomeUnknownObject     LendOutcome = 6
	LendOutcomeInvalid           LendOutcome = 7
	LendOutcomeUnavailable       LendOutcome = 8
)

// String returns v's exact wire word, or the empty string for an invalid value.
func (v LendOutcome) String() string {
	word, _ := v.WireName()
	return word
}

// WireName returns v's exact wire word and whether v names a member.
func (v LendOutcome) WireName() (string, bool) {
	switch v {
	case LendOutcomeLent:
		return "lent", true
	case LendOutcomeNotPermitted:
		return "not_permitted", true
	case LendOutcomeUnsupportedEngine:
		return "unsupported_engine", true
	case LendOutcomeLinkRefused:
		return "link_refused", true
	case LendOutcomeAlreadyLent:
		return "already_lent", true
	case LendOutcomeUnknownObject:
		return "unknown_object", true
	case LendOutcomeInvalid:
		return "invalid", true
	case LendOutcomeUnavailable:
		return "unavailable", true
	}
	return "", false
}

// ParseLendOutcome returns the member named by an exact wire word.
func ParseLendOutcome(word string) (LendOutcome, bool) {
	switch word {
	case "lent":
		return LendOutcomeLent, true
	case "not_permitted":
		return LendOutcomeNotPermitted, true
	case "unsupported_engine":
		return LendOutcomeUnsupportedEngine, true
	case "link_refused":
		return LendOutcomeLinkRefused, true
	case "already_lent":
		return LendOutcomeAlreadyLent, true
	case "unknown_object":
		return LendOutcomeUnknownObject, true
	case "invalid":
		return LendOutcomeInvalid, true
	case "unavailable":
		return LendOutcomeUnavailable, true
	}
	return LendOutcome(0), false
}

// MarshalText preserves the member's exact wire word for standard text users,
// including JSON object keys. Invalid and zero values are refused.
func (v LendOutcome) MarshalText() ([]byte, error) {
	word, ok := v.WireName()
	if !ok {
		return nil, &Refusal{Word: "bad_enum", Offset: 0}
	}
	return []byte(word), nil
}

// UnmarshalText accepts an exact wire word and refuses unknown text.
func (v *LendOutcome) UnmarshalText(text []byte) error {
	word, ok := ParseLendOutcome(string(text))
	if !ok {
		return &Refusal{Word: "bad_enum", Offset: 0}
	}
	*v = word
	return nil
}

// MarshalJSON keeps closed vocabularies as JSON strings rather than their
// private numeric implementation tags.
func (v LendOutcome) MarshalJSON() ([]byte, error) {
	word, ok := v.WireName()
	if !ok {
		return nil, &Refusal{Word: "bad_enum", Offset: 0}
	}
	return esc(nil, word), nil
}

// UnmarshalJSON accepts only an exact JSON string member. Numbers, null and
// unknown strings are refused by the same codec rules as generated records.
func (v *LendOutcome) UnmarshalJSON(data []byte) error {
	r := reader{buf: data}
	r.ws()
	word, err := r.str()
	if err != nil {
		return err
	}
	r.ws()
	if r.pos != len(r.buf) {
		return r.refuse("trailing_bytes")
	}
	parsed, ok := ParseLendOutcome(word)
	if !ok {
		return r.refuse("bad_enum")
	}
	*v = parsed
	return nil
}

// LendOutcomeValues returns every member of LendOutcome in declaration order, in a new slice.
func LendOutcomeValues() []LendOutcome {
	return []LendOutcome{LendOutcomeLent, LendOutcomeNotPermitted, LendOutcomeUnsupportedEngine, LendOutcomeLinkRefused, LendOutcomeAlreadyLent, LendOutcomeUnknownObject, LendOutcomeInvalid, LendOutcomeUnavailable}
}

// Known reports whether v is a member of LendOutcome.
func (v LendOutcome) Known() bool {
	_, ok := v.WireName()
	return ok
}

// UnlendOutcome is a closed vocabulary. Its numeric values are private implementation
// tags; String and ParseUnlendOutcome preserve the exact wire words.
type UnlendOutcome uint32

const (
	UnlendOutcomeUnlent       UnlendOutcome = 1
	UnlendOutcomeNotPermitted UnlendOutcome = 2
	UnlendOutcomeUnknown      UnlendOutcome = 3
	UnlendOutcomeInvalid      UnlendOutcome = 4
	UnlendOutcomeUnavailable  UnlendOutcome = 5
)

// String returns v's exact wire word, or the empty string for an invalid value.
func (v UnlendOutcome) String() string {
	word, _ := v.WireName()
	return word
}

// WireName returns v's exact wire word and whether v names a member.
func (v UnlendOutcome) WireName() (string, bool) {
	switch v {
	case UnlendOutcomeUnlent:
		return "unlent", true
	case UnlendOutcomeNotPermitted:
		return "not_permitted", true
	case UnlendOutcomeUnknown:
		return "unknown", true
	case UnlendOutcomeInvalid:
		return "invalid", true
	case UnlendOutcomeUnavailable:
		return "unavailable", true
	}
	return "", false
}

// ParseUnlendOutcome returns the member named by an exact wire word.
func ParseUnlendOutcome(word string) (UnlendOutcome, bool) {
	switch word {
	case "unlent":
		return UnlendOutcomeUnlent, true
	case "not_permitted":
		return UnlendOutcomeNotPermitted, true
	case "unknown":
		return UnlendOutcomeUnknown, true
	case "invalid":
		return UnlendOutcomeInvalid, true
	case "unavailable":
		return UnlendOutcomeUnavailable, true
	}
	return UnlendOutcome(0), false
}

// MarshalText preserves the member's exact wire word for standard text users,
// including JSON object keys. Invalid and zero values are refused.
func (v UnlendOutcome) MarshalText() ([]byte, error) {
	word, ok := v.WireName()
	if !ok {
		return nil, &Refusal{Word: "bad_enum", Offset: 0}
	}
	return []byte(word), nil
}

// UnmarshalText accepts an exact wire word and refuses unknown text.
func (v *UnlendOutcome) UnmarshalText(text []byte) error {
	word, ok := ParseUnlendOutcome(string(text))
	if !ok {
		return &Refusal{Word: "bad_enum", Offset: 0}
	}
	*v = word
	return nil
}

// MarshalJSON keeps closed vocabularies as JSON strings rather than their
// private numeric implementation tags.
func (v UnlendOutcome) MarshalJSON() ([]byte, error) {
	word, ok := v.WireName()
	if !ok {
		return nil, &Refusal{Word: "bad_enum", Offset: 0}
	}
	return esc(nil, word), nil
}

// UnmarshalJSON accepts only an exact JSON string member. Numbers, null and
// unknown strings are refused by the same codec rules as generated records.
func (v *UnlendOutcome) UnmarshalJSON(data []byte) error {
	r := reader{buf: data}
	r.ws()
	word, err := r.str()
	if err != nil {
		return err
	}
	r.ws()
	if r.pos != len(r.buf) {
		return r.refuse("trailing_bytes")
	}
	parsed, ok := ParseUnlendOutcome(word)
	if !ok {
		return r.refuse("bad_enum")
	}
	*v = parsed
	return nil
}

// UnlendOutcomeValues returns every member of UnlendOutcome in declaration order, in a new slice.
func UnlendOutcomeValues() []UnlendOutcome {
	return []UnlendOutcome{UnlendOutcomeUnlent, UnlendOutcomeNotPermitted, UnlendOutcomeUnknown, UnlendOutcomeInvalid, UnlendOutcomeUnavailable}
}

// Known reports whether v is a member of UnlendOutcome.
func (v UnlendOutcome) Known() bool {
	_, ok := v.WireName()
	return ok
}

// LendsOutcome is a closed vocabulary. Its numeric values are private implementation
// tags; String and ParseLendsOutcome preserve the exact wire words.
type LendsOutcome uint32

const (
	LendsOutcomePage         LendsOutcome = 1
	LendsOutcomeNotPermitted LendsOutcome = 2
	LendsOutcomeInvalid      LendsOutcome = 3
	LendsOutcomeUnavailable  LendsOutcome = 4
)

// String returns v's exact wire word, or the empty string for an invalid value.
func (v LendsOutcome) String() string {
	word, _ := v.WireName()
	return word
}

// WireName returns v's exact wire word and whether v names a member.
func (v LendsOutcome) WireName() (string, bool) {
	switch v {
	case LendsOutcomePage:
		return "page", true
	case LendsOutcomeNotPermitted:
		return "not_permitted", true
	case LendsOutcomeInvalid:
		return "invalid", true
	case LendsOutcomeUnavailable:
		return "unavailable", true
	}
	return "", false
}

// ParseLendsOutcome returns the member named by an exact wire word.
func ParseLendsOutcome(word string) (LendsOutcome, bool) {
	switch word {
	case "page":
		return LendsOutcomePage, true
	case "not_permitted":
		return LendsOutcomeNotPermitted, true
	case "invalid":
		return LendsOutcomeInvalid, true
	case "unavailable":
		return LendsOutcomeUnavailable, true
	}
	return LendsOutcome(0), false
}

// MarshalText preserves the member's exact wire word for standard text users,
// including JSON object keys. Invalid and zero values are refused.
func (v LendsOutcome) MarshalText() ([]byte, error) {
	word, ok := v.WireName()
	if !ok {
		return nil, &Refusal{Word: "bad_enum", Offset: 0}
	}
	return []byte(word), nil
}

// UnmarshalText accepts an exact wire word and refuses unknown text.
func (v *LendsOutcome) UnmarshalText(text []byte) error {
	word, ok := ParseLendsOutcome(string(text))
	if !ok {
		return &Refusal{Word: "bad_enum", Offset: 0}
	}
	*v = word
	return nil
}

// MarshalJSON keeps closed vocabularies as JSON strings rather than their
// private numeric implementation tags.
func (v LendsOutcome) MarshalJSON() ([]byte, error) {
	word, ok := v.WireName()
	if !ok {
		return nil, &Refusal{Word: "bad_enum", Offset: 0}
	}
	return esc(nil, word), nil
}

// UnmarshalJSON accepts only an exact JSON string member. Numbers, null and
// unknown strings are refused by the same codec rules as generated records.
func (v *LendsOutcome) UnmarshalJSON(data []byte) error {
	r := reader{buf: data}
	r.ws()
	word, err := r.str()
	if err != nil {
		return err
	}
	r.ws()
	if r.pos != len(r.buf) {
		return r.refuse("trailing_bytes")
	}
	parsed, ok := ParseLendsOutcome(word)
	if !ok {
		return r.refuse("bad_enum")
	}
	*v = parsed
	return nil
}

// LendsOutcomeValues returns every member of LendsOutcome in declaration order, in a new slice.
func LendsOutcomeValues() []LendsOutcome {
	return []LendsOutcome{LendsOutcomePage, LendsOutcomeNotPermitted, LendsOutcomeInvalid, LendsOutcomeUnavailable}
}

// Known reports whether v is a member of LendsOutcome.
func (v LendsOutcome) Known() bool {
	_, ok := v.WireName()
	return ok
}

// ServiceErrorCode is an open vocabulary: a reader keeps a word it has never heard, so
// a value may be none of the constants below. ServiceErrorCode(word) and string(v)
// convert between the raw word and the vocabulary.
type ServiceErrorCode string

const (
	ServiceErrorCodeHandlerError      ServiceErrorCode = "handler_error"
	ServiceErrorCodeInvalidResult     ServiceErrorCode = "invalid_result"
	ServiceErrorCodeUnknownVersion    ServiceErrorCode = "unknown_version"
	ServiceErrorCodeUnknownService    ServiceErrorCode = "unknown_service"
	ServiceErrorCodeUnknownMethod     ServiceErrorCode = "unknown_method"
	ServiceErrorCodeWrongMode         ServiceErrorCode = "wrong_mode"
	ServiceErrorCodeCallerUnavailable ServiceErrorCode = "caller_unavailable"
	ServiceErrorCodeIdentityRequired  ServiceErrorCode = "identity_required"
)

// ServiceErrorCodeValues returns every member of ServiceErrorCode in declaration order, in a new slice.
func ServiceErrorCodeValues() []ServiceErrorCode {
	return []ServiceErrorCode{ServiceErrorCodeHandlerError, ServiceErrorCodeInvalidResult, ServiceErrorCodeUnknownVersion, ServiceErrorCodeUnknownService, ServiceErrorCodeUnknownMethod, ServiceErrorCodeWrongMode, ServiceErrorCodeCallerUnavailable, ServiceErrorCodeIdentityRequired}
}

// Known reports whether v is a member of ServiceErrorCode.
func (v ServiceErrorCode) Known() bool {
	switch v {
	case ServiceErrorCodeHandlerError, ServiceErrorCodeInvalidResult, ServiceErrorCodeUnknownVersion, ServiceErrorCodeUnknownService, ServiceErrorCodeUnknownMethod, ServiceErrorCodeWrongMode, ServiceErrorCodeCallerUnavailable, ServiceErrorCodeIdentityRequired:
		return true
	}
	return false
}

var LendingErrorCodes = []string{"caller_unavailable", "identity_required"}

// One lend the ledger holds. id names this entry and is what Unlend takes.
// engine is the declared host name the file was lent to. store and object are
// the inventory's own naming of the source: object is the id Lend was given,
// resolved to the manifest id when the source publishes one. name is the
// engine's directory name for the borrowed file, which is what that engine's
// own list is expected to derive its model name from. link is the absolute path
// of the link this lend created, in the engine's directory. size is the source
// file's size in bytes at the time of the lend. The ledger, not the engine's
// list, says whether a lend is in force.
type Lend struct {
	ID      string
	Engine  string
	Store   string
	Object  string
	Name    string
	Link    string
	Kind    Link
	Size    int64
	Created string
}

// lend is present exactly for lent and already_lent; already_lent carries the
// entry that already holds this object at this engine. detail is display-grade
// text naming the refused case and carries no path for a caller that may not
// read one; it is empty for lent.
type LendResult struct {
	Outcome LendOutcome
	Lend    *Lend
	Detail  string
}

// unlent means the link and every directory this lend created are gone from the
// engine's directory, the source is untouched, and the entry has left the
// ledger. unknown is an entry no ledger row names, including one already
// unlent. detail is display-grade and empty for unlent.
type UnlendResult struct {
	Outcome UnlendOutcome
	Detail  string
}

// One page of the ledger in created order, oldest first. complete means the
// ledger is exhausted; otherwise continuation is nonempty. Refusals carry no
// entries, an empty continuation and complete false.
type LendPage struct {
	Outcome      LendsOutcome
	Lends        []Lend
	Continuation string
	Complete     bool
}

type oaLendingLendArguments struct {
	Store  string
	Object string
	Engine string
	Copy   bool
}

type oaLendingUnlendArguments struct {
	Entry string
}

type oaLendingLendsArguments struct {
	Continuation string
	Limit        int64
}

type oaServiceFrame struct {
	Version   int32
	Service   string
	Method    string
	Arguments Raw
}

type oaServiceReply struct {
	Version int32
	Service string
	Method  string
	Ok      bool
	Payload Raw
}

type oaServiceError struct {
	Code    string
	Message string
}

type oaLendingLendResult struct {
	Value LendResult
}

type oaLendingUnlendResult struct {
	Value UnlendResult
}

type oaLendingLendsResult struct {
	Value LendPage
}

func encLend(out []byte, v *Lend, depth int) []byte {
	if !(v.Kind).Known() {
		panic(&Refusal{Word: "bad_enum", Offset: 0})
	}
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "id")
	out = append(out, ':', ' ')
	out = esc(out, v.ID)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "engine")
	out = append(out, ':', ' ')
	out = esc(out, v.Engine)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "store")
	out = append(out, ':', ' ')
	out = esc(out, v.Store)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "object")
	out = append(out, ':', ' ')
	out = esc(out, v.Object)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "name")
	out = append(out, ':', ' ')
	out = esc(out, v.Name)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "link")
	out = append(out, ':', ' ')
	out = esc(out, v.Link)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "kind")
	out = append(out, ':', ' ')
	out = esc(out, v.Kind.String())
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "size")
	out = append(out, ':', ' ')
	out = num(out, v.Size)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "created")
	out = append(out, ':', ' ')
	out = esc(out, writeTimestamp(v.Created))
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encLendResult(out []byte, v *LendResult, depth int) []byte {
	if !(v.Outcome).Known() {
		panic(&Refusal{Word: "bad_enum", Offset: 0})
	}
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "outcome")
	out = append(out, ':', ' ')
	out = esc(out, v.Outcome.String())
	if v.Lend != nil {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "lend")
		out = append(out, ':', ' ')
		out = encLend(out, v.Lend, depth+1)
	}
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "detail")
	out = append(out, ':', ' ')
	out = esc(out, v.Detail)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encUnlendResult(out []byte, v *UnlendResult, depth int) []byte {
	if !(v.Outcome).Known() {
		panic(&Refusal{Word: "bad_enum", Offset: 0})
	}
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "outcome")
	out = append(out, ':', ' ')
	out = esc(out, v.Outcome.String())
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "detail")
	out = append(out, ':', ' ')
	out = esc(out, v.Detail)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encLendPage(out []byte, v *LendPage, depth int) []byte {
	if !(v.Outcome).Known() {
		panic(&Refusal{Word: "bad_enum", Offset: 0})
	}
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "outcome")
	out = append(out, ':', ' ')
	out = esc(out, v.Outcome.String())
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "lends")
	out = append(out, ':', ' ')
	out = encList(out, v.Lends, depth+1, encLend)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "continuation")
	out = append(out, ':', ' ')
	out = esc(out, v.Continuation)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "complete")
	out = append(out, ':', ' ')
	if v.Complete {
		out = append(out, 't', 'r', 'u', 'e')
	} else {
		out = append(out, 'f', 'a', 'l', 's', 'e')
	}
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOALendingLendArguments(out []byte, v *oaLendingLendArguments, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "store")
	out = append(out, ':', ' ')
	out = esc(out, v.Store)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "object")
	out = append(out, ':', ' ')
	out = esc(out, v.Object)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "engine")
	out = append(out, ':', ' ')
	out = esc(out, v.Engine)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "copy")
	out = append(out, ':', ' ')
	if v.Copy {
		out = append(out, 't', 'r', 'u', 'e')
	} else {
		out = append(out, 'f', 'a', 'l', 's', 'e')
	}
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOALendingUnlendArguments(out []byte, v *oaLendingUnlendArguments, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "entry")
	out = append(out, ':', ' ')
	out = esc(out, v.Entry)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOALendingLendsArguments(out []byte, v *oaLendingLendsArguments, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "continuation")
	out = append(out, ':', ' ')
	out = esc(out, v.Continuation)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "limit")
	out = append(out, ':', ' ')
	out = num(out, v.Limit)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAServiceFrame(out []byte, v *oaServiceFrame, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "version")
	out = append(out, ':', ' ')
	out = num(out, int64(v.Version))
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "service")
	out = append(out, ':', ' ')
	out = esc(out, v.Service)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "method")
	out = append(out, ':', ' ')
	out = esc(out, v.Method)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "arguments")
	out = append(out, ':', ' ')
	out = append(out, v.Arguments...)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAServiceReply(out []byte, v *oaServiceReply, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "version")
	out = append(out, ':', ' ')
	out = num(out, int64(v.Version))
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "service")
	out = append(out, ':', ' ')
	out = esc(out, v.Service)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "method")
	out = append(out, ':', ' ')
	out = esc(out, v.Method)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "ok")
	out = append(out, ':', ' ')
	if v.Ok {
		out = append(out, 't', 'r', 'u', 'e')
	} else {
		out = append(out, 'f', 'a', 'l', 's', 'e')
	}
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "payload")
	out = append(out, ':', ' ')
	out = append(out, v.Payload...)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAServiceError(out []byte, v *oaServiceError, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "code")
	out = append(out, ':', ' ')
	out = esc(out, v.Code)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "message")
	out = append(out, ':', ' ')
	out = esc(out, v.Message)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOALendingLendResult(out []byte, v *oaLendingLendResult, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "value")
	out = append(out, ':', ' ')
	out = encLendResult(out, &v.Value, depth+1)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOALendingUnlendResult(out []byte, v *oaLendingUnlendResult, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "value")
	out = append(out, ':', ' ')
	out = encUnlendResult(out, &v.Value, depth+1)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOALendingLendsResult(out []byte, v *oaLendingLendsResult, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "value")
	out = append(out, ':', ' ')
	out = encLendPage(out, &v.Value, depth+1)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func Encode(v *LendResult) []byte {
	return append(encLendResult(nil, v, 0), '\n')
}

type Refusal struct {
	Word   string
	Offset int
}

func (r *Refusal) Error() string {
	return "refused: " + r.Word + " at byte " + decimal(int64(r.Offset))
}

func decimal(n int64) string { return string(num(nil, n)) }

const depthLimit = 64

type reader struct {
	buf   []byte
	pos   int
	depth int
}

func (r *reader) refuse(word string) error { return &Refusal{Word: word, Offset: r.pos} }

func (r *reader) at() byte {
	if r.pos < len(r.buf) {
		return r.buf[r.pos]
	}
	return 0
}

func (r *reader) ws() {
	for r.pos < len(r.buf) {
		switch r.buf[r.pos] {
		case ' ', '\t', '\n', '\r':
			r.pos++
		default:
			return
		}
	}
}

func (r *reader) enter() error {
	r.depth++
	if r.depth > depthLimit {
		return r.refuse("depth_exceeded")
	}
	return nil
}

func (r *reader) str() (string, error) {
	if r.at() != '"' {
		return "", r.refuse("wrong_type")
	}
	r.pos++
	var out []byte
	for {
		if r.pos >= len(r.buf) {
			return "", r.refuse("malformed")
		}
		c := r.buf[r.pos]
		switch {
		case c == '"':
			r.pos++
			if !validUTF8(out) {
				return "", r.refuse("bad_string")
			}
			return string(out), nil
		case c < 0x20:
			return "", r.refuse("bad_string")
		case c == '\\':
			var err error
			if out, err = r.escape(out); err != nil {
				return "", err
			}
		default:
			out = append(out, c)
			r.pos++
		}
	}
}

func (r *reader) escape(out []byte) ([]byte, error) {
	r.pos++
	if r.pos >= len(r.buf) {
		return nil, r.refuse("malformed")
	}
	c := r.buf[r.pos]
	r.pos++
	switch c {
	case '"', '\\', '/':
		return append(out, c), nil
	case 'b':
		return append(out, 0x08), nil
	case 'f':
		return append(out, 0x0c), nil
	case 'n':
		return append(out, '\n'), nil
	case 'r':
		return append(out, '\r'), nil
	case 't':
		return append(out, '\t'), nil
	case 'u':
		u, err := r.hex4()
		if err != nil {
			return nil, err
		}
		if u >= 0xDC00 && u <= 0xDFFF {
			return nil, r.refuse("bad_string")
		}
		if u >= 0xD800 && u <= 0xDBFF {
			if r.pos+1 >= len(r.buf) || r.buf[r.pos] != '\\' || r.buf[r.pos+1] != 'u' {
				return nil, r.refuse("bad_string")
			}
			r.pos += 2
			lo, err := r.hex4()
			if err != nil {
				return nil, err
			}
			if lo < 0xDC00 || lo > 0xDFFF {
				return nil, r.refuse("bad_string")
			}
			u = 0x10000 + (u-0xD800)<<10 + (lo - 0xDC00)
		}
		return appendRune(out, u), nil
	}
	return nil, r.refuse("bad_string")
}

func (r *reader) hex4() (int32, error) {
	if r.pos+4 > len(r.buf) {
		return 0, r.refuse("bad_string")
	}
	var u int32
	for i := 0; i < 4; i++ {
		c := r.buf[r.pos+i]
		switch {
		case c >= '0' && c <= '9':
			u = u<<4 | int32(c-'0')
		case c >= 'a' && c <= 'f':
			u = u<<4 | int32(c-'a'+10)
		case c >= 'A' && c <= 'F':
			u = u<<4 | int32(c-'A'+10)
		default:
			return 0, r.refuse("bad_string")
		}
	}
	r.pos += 4
	return u, nil
}

func appendRune(out []byte, cp int32) []byte {
	switch {
	case cp < 0x80:
		return append(out, byte(cp))
	case cp < 0x800:
		return append(out, byte(0xC0|cp>>6), byte(0x80|cp&0x3F))
	case cp < 0x10000:
		return append(out, byte(0xE0|cp>>12), byte(0x80|cp>>6&0x3F), byte(0x80|cp&0x3F))
	}
	return append(out, byte(0xF0|cp>>18), byte(0x80|cp>>12&0x3F), byte(0x80|cp>>6&0x3F), byte(0x80|cp&0x3F))
}

func validUTF8(b []byte) bool {
	for i := 0; i < len(b); {
		c := b[i]
		var n int
		var cp int32
		switch {
		case c < 0x80:
			i++
			continue
		case c>>5 == 0x6:
			n, cp = 2, int32(c&0x1F)
		case c>>4 == 0xE:
			n, cp = 3, int32(c&0x0F)
		case c>>3 == 0x1E:
			n, cp = 4, int32(c&0x07)
		default:
			return false
		}
		if i+n > len(b) {
			return false
		}
		for k := 1; k < n; k++ {
			if b[i+k]>>6 != 0x2 {
				return false
			}
			cp = cp<<6 | int32(b[i+k]&0x3F)
		}
		lowest := []int32{0, 0, 0x80, 0x800, 0x10000}[n]
		if cp < lowest || cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF) {
			return false
		}
		i += n
	}
	return true
}

func (r *reader) integer(min, max int64) (int64, error) {
	c := r.at()
	if c != '-' && (c < '0' || c > '9') {
		return 0, r.refuse("wrong_type")
	}
	neg := c == '-'
	if neg {
		r.pos++
	}
	d := r.at()
	if d < '0' || d > '9' {
		return 0, r.refuse("malformed")
	}
	var u uint64
	if d == '0' {
		r.pos++
	} else {
		for d = r.at(); d >= '0' && d <= '9'; d = r.at() {
			if u > 922337203685477580 {
				return 0, r.refuse("number_spelling")
			}
			u = u*10 + uint64(d-'0')
			r.pos++
		}
	}
	switch c := r.at(); {
	case c == '.' || c == 'e' || c == 'E' || (c >= '0' && c <= '9'):
		return 0, r.refuse("number_spelling")
	}
	if neg && u == 0 {
		return 0, r.refuse("number_spelling")
	}
	var n int64
	switch {
	case neg && u == 1<<63:
		n = -1 << 63
	case u > 1<<63-1:
		return 0, r.refuse("number_spelling")
	case neg:
		n = -int64(u)
	default:
		n = int64(u)
	}
	if n < min || n > max {
		return 0, r.refuse("number_spelling")
	}
	return n, nil
}

func (r *reader) boolean() (bool, error) {
	switch r.at() {
	case 't':
		return true, r.literal("true")
	case 'f':
		return false, r.literal("false")
	}
	return false, r.refuse("wrong_type")
}

func (r *reader) literal(word string) error {
	if r.pos+len(word) > len(r.buf) || string(r.buf[r.pos:r.pos+len(word)]) != word {
		return r.refuse("malformed")
	}
	r.pos += len(word)
	return nil
}

func (r *reader) strList() ([]string, error) {
	if r.at() != '[' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	out := []string{}
	r.ws()
	if r.at() != ']' {
		for {
			r.ws()
			s, err := r.str()
			if err != nil {
				return nil, err
			}
			out = append(out, s)
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != ']' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return out, nil
}

func (r *reader) rawMap() (map[string]Raw, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	out := map[string]Raw{}
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			k, err := r.str()
			if err != nil {
				return nil, err
			}
			if _, again := out[k]; again {
				return nil, r.refuse("duplicate_key")
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			v, err := r.rawValue()
			if err != nil {
				return nil, err
			}
			out[k] = v
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return out, nil
}

func (r *reader) rawValue() (Raw, error) {
	start := r.pos
	if err := r.skipValue(); err != nil {
		return "", err
	}
	return Raw(r.buf[start:r.pos]), nil
}

func (r *reader) skipValue() error {
	c := r.at()
	switch {
	case c == '"':
		return r.skipString()
	case c == '{' || c == '[':
		return r.skipContainer()
	case c == 't':
		return r.literal("true")
	case c == 'f':
		return r.literal("false")
	case c == 'n':
		return r.literal("null")
	case c == '-' || (c >= '0' && c <= '9'):
		return r.skipNumber()
	}
	return r.refuse("malformed")
}

// An opaque value is validated and carried, never interpreted. Its syntax is
// the record's own — the same string reader, so an escape, a control byte or a
// lone surrogate is judged identically at any depth — and what it is free to
// spell, it keeps: the bytes between these two offsets are what a writer
// re-emits. A number is walked, never converted, so a value no host type holds
// survives the reader that carried it.
func (r *reader) skipString() error {
	_, err := r.str()
	return err
}

func (r *reader) skipNumber() error {
	if r.at() == '-' {
		r.pos++
	}
	switch c := r.at(); {
	case c == '0':
		r.pos++
	case c >= '1' && c <= '9':
		for c := r.at(); c >= '0' && c <= '9'; c = r.at() {
			r.pos++
		}
	default:
		return r.refuse("number_spelling")
	}
	if r.at() == '.' {
		r.pos++
		if err := r.someDigits(); err != nil {
			return err
		}
	}
	if c := r.at(); c == 'e' || c == 'E' {
		r.pos++
		if c := r.at(); c == '+' || c == '-' {
			r.pos++
		}
		if err := r.someDigits(); err != nil {
			return err
		}
	}
	return nil
}

func (r *reader) someDigits() error {
	n := 0
	for c := r.at(); c >= '0' && c <= '9'; c = r.at() {
		r.pos++
		n++
	}
	if n == 0 {
		return r.refuse("number_spelling")
	}
	return nil
}

func (r *reader) skipContainer() error {
	open := r.buf[r.pos]
	shut := byte('}')
	if open == '[' {
		shut = ']'
	}
	if err := r.enter(); err != nil {
		return err
	}
	r.pos++
	r.ws()
	seen := map[string]bool{}
	if r.at() != shut {
		for {
			r.ws()
			if open == '{' {
				if r.at() != '"' {
					return r.refuse("malformed")
				}
				k, err := r.str()
				if err != nil {
					return err
				}
				if seen[k] {
					return r.refuse("duplicate_key")
				}
				seen[k] = true
				r.ws()
				if r.at() != ':' {
					return r.refuse("malformed")
				}
				r.pos++
				r.ws()
			}
			if err := r.skipValue(); err != nil {
				return err
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != shut {
		return r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return nil
}

func decodeList[T any](r *reader, elem func(*reader) (*T, error)) ([]T, error) {
	if r.at() != '[' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	out := []T{}
	r.ws()
	if r.at() != ']' {
		for {
			r.ws()
			v, err := elem(r)
			if err != nil {
				return nil, err
			}
			out = append(out, *v)
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != ']' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return out, nil
}

func digits(s string, i, n int) bool {
	if i+n > len(s) {
		return false
	}
	for k := 0; k < n; k++ {
		if s[i+k] < '0' || s[i+k] > '9' {
			return false
		}
	}
	return true
}

func datePart(s string) bool {
	return len(s) >= 19 && digits(s, 0, 4) && s[4] == '-' && digits(s, 5, 2) && s[7] == '-' &&
		digits(s, 8, 2) && digits(s, 11, 2) && s[13] == ':' && digits(s, 14, 2) && s[16] == ':' && digits(s, 17, 2)
}

// [DEF-G1] rfc3339-wide: what a reader accepts. Any fraction of one to nine
// digits or none, either case of the separators, and a numeric offset.
func lexicalTimestamp(s string) bool {
	if !datePart(s) || (s[10] != 'T' && s[10] != 't') {
		return false
	}
	i := 19
	if i < len(s) && s[i] == '.' {
		i++
		n := 0
		for i < len(s) && s[i] >= '0' && s[i] <= '9' {
			i++
			n++
		}
		if n < 1 || n > 9 {
			return false
		}
	}
	if i >= len(s) {
		return false
	}
	if s[i] == 'Z' || s[i] == 'z' {
		return i+1 == len(s)
	}
	if s[i] != '+' && s[i] != '-' {
		return false
	}
	return len(s) == i+6 && digits(s, i+1, 2) && s[i+3] == ':' && digits(s, i+4, 2)
}

// [DEF-G2] rfc3339-micros: what a writer emits. Exactly six fractional digits,
// upper-case separators, UTC.
func microsTimestamp(s string) bool {
	return len(s) == 27 && normalizedTimestamp(s) == s
}

func (r *reader) timestamp() (string, error) {
	at := r.pos
	s, err := r.str()
	if err != nil {
		return "", err
	}
	if !wideTimestamp(s) {
		r.pos = at
		return "", r.refuse("bad_timestamp")
	}
	return s, nil
}

func timestampNumber(s string, i, n int) int {
	v := 0
	for k := 0; k < n; k++ {
		v = v*10 + int(s[i+k]-'0')
	}
	return v
}
func timestampDays(y, m int) int {
	if m == 2 {
		if y%4 == 0 && (y%100 != 0 || y%400 == 0) {
			return 29
		}
		return 28
	}
	if m == 4 || m == 6 || m == 9 || m == 11 {
		return 30
	}
	return 31
}
func normalizedTimestamp(s string) string {
	if !lexicalTimestamp(s) {
		return ""
	}
	y, m, d := timestampNumber(s, 0, 4), timestampNumber(s, 5, 2), timestampNumber(s, 8, 2)
	h, minute, sec := timestampNumber(s, 11, 2), timestampNumber(s, 14, 2), timestampNumber(s, 17, 2)
	if m < 1 || m > 12 || d < 1 || d > timestampDays(y, m) || h > 23 || minute > 59 || sec > 59 {
		return ""
	}
	i, fraction := 19, ""
	if s[i] == '.' {
		i++
		start := i
		for s[i] >= '0' && s[i] <= '9' {
			i++
		}
		fraction = s[start:i]
	}
	total := h*60 + minute
	if s[i] == '+' || s[i] == '-' {
		oh, om := timestampNumber(s, i+1, 2), timestampNumber(s, i+4, 2)
		if oh > 23 || om > 59 {
			return ""
		}
		offset := oh*60 + om
		if s[i] == '+' {
			total -= offset
		} else {
			total += offset
		}
	}
	if total < 0 {
		total += 1440
		d--
	} else if total >= 1440 {
		total -= 1440
		d++
	}
	if d == 0 {
		m--
		if m == 0 {
			y--
			m = 12
		}
		d = timestampDays(y, m)
	}
	if d > timestampDays(y, m) {
		d = 1
		m++
		if m == 13 {
			y++
			m = 1
		}
	}
	if y < 0 || y > 9999 {
		return ""
	}
	out := []byte("0000-00-00T00:00:00.000000Z")
	put := func(at, width, value int) {
		for k := width - 1; k >= 0; k-- {
			out[at+k] = byte(value%10) + '0'
			value /= 10
		}
	}
	put(0, 4, y)
	put(5, 2, m)
	put(8, 2, d)
	put(11, 2, total/60)
	put(14, 2, total%60)
	put(17, 2, sec)
	for k := 0; k < 6 && k < len(fraction); k++ {
		out[20+k] = fraction[k]
	}
	return string(out)
}
func wideTimestamp(s string) bool { return normalizedTimestamp(s) != "" }
func writeTimestamp(s string) string {
	result := normalizedTimestamp(s)
	if result == "" {
		panic(&Refusal{Word: "bad_timestamp", Offset: 0})
	}
	return result
}

func (r *reader) decodeLend() (*Lend, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &Lend{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "id":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.ID = x
			case "engine":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Engine = x
			case "store":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Store = x
			case "object":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Object = x
			case "name":
				if seen&16 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 16
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Name = x
			case "link":
				if seen&32 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 32
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Link = x
			case "kind":
				if seen&64 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 64
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				word, ok := ParseLink(x)
				if !ok {
					return nil, r.refuse("bad_enum")
				}
				v.Kind = word
			case "size":
				if seen&128 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 128
				x, err := r.integer(-9223372036854775808, 9223372036854775807)
				if err != nil {
					return nil, err
				}
				v.Size = x
			case "created":
				if seen&256 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 256
				x, err := r.timestamp()
				if err != nil {
					return nil, err
				}
				v.Created = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&511 != 511 {
		return nil, r.refuse("missing_field")
	}
	if !(v.Kind).Known() {
		return nil, r.refuse("bad_enum")
	}
	return v, nil
}

func (r *reader) decodeLendResult() (*LendResult, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &LendResult{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "outcome":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				word, ok := ParseLendOutcome(x)
				if !ok {
					return nil, r.refuse("bad_enum")
				}
				v.Outcome = word
			case "lend":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.decodeLend()
				if err != nil {
					return nil, err
				}
				v.Lend = x
			case "detail":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Detail = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&5 != 5 {
		return nil, r.refuse("missing_field")
	}
	if !(v.Outcome).Known() {
		return nil, r.refuse("bad_enum")
	}
	return v, nil
}

func (r *reader) decodeUnlendResult() (*UnlendResult, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &UnlendResult{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "outcome":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				word, ok := ParseUnlendOutcome(x)
				if !ok {
					return nil, r.refuse("bad_enum")
				}
				v.Outcome = word
			case "detail":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Detail = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&3 != 3 {
		return nil, r.refuse("missing_field")
	}
	if !(v.Outcome).Known() {
		return nil, r.refuse("bad_enum")
	}
	return v, nil
}

func (r *reader) decodeLendPage() (*LendPage, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &LendPage{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "outcome":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				word, ok := ParseLendsOutcome(x)
				if !ok {
					return nil, r.refuse("bad_enum")
				}
				v.Outcome = word
			case "lends":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := decodeList(r, (*reader).decodeLend)
				if err != nil {
					return nil, err
				}
				v.Lends = x
			case "continuation":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Continuation = x
			case "complete":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.boolean()
				if err != nil {
					return nil, err
				}
				v.Complete = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&15 != 15 {
		return nil, r.refuse("missing_field")
	}
	if !(v.Outcome).Known() {
		return nil, r.refuse("bad_enum")
	}
	return v, nil
}

func (r *reader) decodeOALendingLendArguments() (*oaLendingLendArguments, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &oaLendingLendArguments{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "store":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Store = x
			case "object":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Object = x
			case "engine":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Engine = x
			case "copy":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.boolean()
				if err != nil {
					return nil, err
				}
				v.Copy = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&15 != 15 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOALendingUnlendArguments() (*oaLendingUnlendArguments, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &oaLendingUnlendArguments{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "entry":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Entry = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOALendingLendsArguments() (*oaLendingLendsArguments, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &oaLendingLendsArguments{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "continuation":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Continuation = x
			case "limit":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.integer(-9223372036854775808, 9223372036854775807)
				if err != nil {
					return nil, err
				}
				v.Limit = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&3 != 3 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAServiceFrame() (*oaServiceFrame, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &oaServiceFrame{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "version":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.integer(-2147483648, 2147483647)
				if err != nil {
					return nil, err
				}
				v.Version = int32(x)
			case "service":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Service = x
			case "method":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Method = x
			case "arguments":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.rawValue()
				if err != nil {
					return nil, err
				}
				v.Arguments = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&15 != 15 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAServiceReply() (*oaServiceReply, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &oaServiceReply{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "version":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.integer(-2147483648, 2147483647)
				if err != nil {
					return nil, err
				}
				v.Version = int32(x)
			case "service":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Service = x
			case "method":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Method = x
			case "ok":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.boolean()
				if err != nil {
					return nil, err
				}
				v.Ok = x
			case "payload":
				if seen&16 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 16
				x, err := r.rawValue()
				if err != nil {
					return nil, err
				}
				v.Payload = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&31 != 31 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAServiceError() (*oaServiceError, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &oaServiceError{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "code":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Code = x
			case "message":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Message = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&3 != 3 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOALendingLendResult() (*oaLendingLendResult, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &oaLendingLendResult{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "value":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeLendResult()
				if err != nil {
					return nil, err
				}
				v.Value = *x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOALendingUnlendResult() (*oaLendingUnlendResult, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &oaLendingUnlendResult{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "value":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeUnlendResult()
				if err != nil {
					return nil, err
				}
				v.Value = *x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOALendingLendsResult() (*oaLendingLendsResult, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &oaLendingLendsResult{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "value":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeLendPage()
				if err != nil {
					return nil, err
				}
				v.Value = *x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func Decode(in []byte) (*LendResult, error) {
	r := &reader{buf: in}
	r.ws()
	v, err := r.decodeLendResult()
	if err != nil {
		return nil, err
	}
	r.ws()
	if r.pos < len(r.buf) {
		return nil, r.refuse("trailing_bytes")
	}
	return v, nil
}

// refusals is in the order two of them are chosen between.

var refusals = []string{"malformed", "bad_string", "number_spelling", "wrong_type", "bad_timestamp", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"}

func refusalRank(word string) int {
	for i, w := range refusals {
		if w == word {
			return i
		}
	}
	return -1
}

// A transport consumes or copies frames before returning. WriteFrame is one-way.
type FrameWriter interface{ WriteFrame(frame []byte) error }
type DispatchError string

func (e DispatchError) Error() string { return string(e) }
func servicePayload(frame []byte) (*oaServiceFrame, error) {
	r := &reader{buf: frame}
	r.ws()
	v, err := r.decodeOAServiceFrame()
	if err != nil {
		return nil, err
	}
	r.ws()
	if r.pos != len(r.buf) {
		return nil, r.refuse("trailing_bytes")
	}
	if v.Version != 1 {
		return nil, DispatchError("unknown_version")
	}
	return v, nil
}

// ExchangeFrame returns the response associated with this call. Correlation,
// serialization and deadlines belong to the transport, not this codec.
type FrameExchanger interface {
	ExchangeFrame(frame []byte) ([]byte, error)
}

// ServiceError is a reply on the error channel. Code is a ServiceErrorCode
// constant or a word this package has never heard.
type ServiceError struct {
	Code    ServiceErrorCode
	Message string
}

func (e *ServiceError) Error() string {
	if e.Message != "" {
		return e.Message
	}
	return string(e.Code)
}
func serviceResponse(frame []byte, service, method string) (Raw, error) {
	r := &reader{buf: frame}
	r.ws()
	v, err := r.decodeOAServiceReply()
	if err != nil {
		return "", err
	}
	r.ws()
	if r.pos != len(r.buf) {
		return "", r.refuse("trailing_bytes")
	}
	if v.Version != 1 {
		return "", DispatchError("unknown_version")
	}
	if v.Service != service || v.Method != method {
		return "", DispatchError("mismatched_response")
	}
	if !v.Ok {
		r = &reader{buf: []byte(v.Payload), depth: 1}
		r.ws()
		e, err := r.decodeOAServiceError()
		if err != nil {
			return "", err
		}
		r.ws()
		if r.pos != len(r.buf) {
			return "", r.refuse("trailing_bytes")
		}
		if e.Code == "" {
			return "", DispatchError("invalid_error")
		}
		return "", &ServiceError{Code: ServiceErrorCode(e.Code), Message: e.Message}
	}
	return v.Payload, nil
}
func serviceReply(v *oaServiceFrame, payload Raw, err error) (frame []byte, outErr error) {
	defer func() {
		if p := recover(); p != nil {
			if e, ok := p.(*Refusal); ok {
				frame = nil
				outErr = e
			} else {
				panic(p)
			}
		}
	}()
	reply := oaServiceReply{Version: 1, Service: v.Service, Method: v.Method, Ok: err == nil, Payload: payload}
	if err != nil {
		e := oaServiceError{Code: string(ServiceErrorCodeHandlerError), Message: "handler failed"}
		switch x := err.(type) {
		case *ServiceError:
			if x.Code != "" {
				e.Code = string(x.Code)
			}
			e.Message = x.Message
		case DispatchError:
			e.Code = string(x)
			e.Message = ""
		case *Refusal:
			e.Code = x.Word
			e.Message = ""
		}
		reply.Payload = Raw(encOAServiceError(nil, &e, 1))
	}
	frame = encOAServiceReply(nil, &reply, 0)
	// Validate even error diagnostics before making them visible on the wire.
	r := &reader{buf: frame}
	r.ws()
	if _, e := r.decodeOAServiceReply(); e != nil {
		return nil, e
	}
	return frame, nil
}

// EndpointContract is abstraction.facade/endpoint@1, which every dispatcher
// answers beside its own service.
const EndpointContract = "abstraction.facade/endpoint@1"

// DescribedService is a dispatcher of any generated package, as
// abstraction.facade/endpoint@1 Describe lists it.
type DescribedService interface {
	DescribeService() (contract string, ready bool, why string)
}

// DescribeEndpoint answers an abstraction.facade/endpoint@1 Describe frame for
// an endpoint hosting services, in that order. program and version are the
// provider's own display name and version, never authority. A frame for another
// service reads unknown_service.
func DescribeEndpoint(frame []byte, program, version string, services ...DescribedService) ([]byte, error) {
	v, err := servicePayload(frame)
	if err != nil {
		return nil, err
	}
	if v.Service != EndpointContract {
		return serviceReply(v, "", DispatchError("unknown_service"))
	}
	if v.Method != "Describe" {
		return serviceReply(v, "", DispatchError("unknown_method"))
	}
	r := &reader{buf: []byte(v.Arguments)}
	r.ws()
	empty := false
	if r.pos < len(r.buf) && r.buf[r.pos] == '{' {
		r.pos++
		r.ws()
		if r.pos < len(r.buf) && r.buf[r.pos] == '}' {
			r.pos++
			r.ws()
			empty = r.pos == len(r.buf)
		}
	}
	if !empty {
		return serviceReply(v, "", &Refusal{Word: "unknown_field"})
	}
	out := append([]byte(nil), "{\"value\":{\"outcome\":\"described\",\"program\":"...)
	out = esc(out, program)
	out = append(out, ",\"version\":"...)
	out = esc(out, version)
	out = append(out, ",\"services\":["...)
	for i, service := range services {
		contract, ready, why := service.DescribeService()
		readiness := "ready"
		if ready {
			why = ""
		} else {
			readiness = "not_ready"
		}
		var guarantees []string
		var capabilities map[string]string
		if described, ok := service.(interface {
			DescribeServiceMetadata() ([]string, map[string]string)
		}); ok {
			guarantees, capabilities = described.DescribeServiceMetadata()
		}
		if i > 0 {
			out = append(out, ',')
		}
		out = append(out, "{\"contract\":"...)
		out = esc(out, contract)
		out = append(out, ",\"readiness\":\""+readiness+"\",\"why\":"...)
		out = esc(out, why)
		out = append(out, ",\"guarantees\":["...)
		for j, guarantee := range guarantees {
			if j > 0 {
				out = append(out, ',')
			}
			out = esc(out, guarantee)
		}
		out = append(out, "],\"capabilities\":{"...)
		for j, key := range sortedKeys(capabilities) {
			if j > 0 {
				out = append(out, ',')
			}
			out = esc(out, key)
			out = append(out, ':')
			out = esc(out, capabilities[key])
		}
		out = append(out, "}}"...)
	}
	return serviceReply(v, Raw(append(out, "]}}"...)), nil)
}

// ServedService is a dispatcher of any generated package that ServeEndpoint
// routes frames to by its wire name.
type ServedService interface {
	DescribedService
	ServiceContract() string
}

// ServeEndpoint answers one request-response frame for an endpoint hosting
// services. A Describe frame lists all of them in the order given; any other
// frame goes to the service it names. A service that takes only one-way frames
// reads wrong_mode, and a frame naming none of them reads unknown_service.
func ServeEndpoint(frame []byte, program, version string, services ...ServedService) ([]byte, error) {
	v, err := servicePayload(frame)
	if err != nil {
		return nil, err
	}
	if v.Service == EndpointContract {
		described := make([]DescribedService, len(services))
		for i, service := range services {
			described[i] = service
		}
		return DescribeEndpoint(frame, program, version, described...)
	}
	for _, service := range services {
		if service.ServiceContract() != v.Service {
			continue
		}
		if exchanger, ok := service.(interface{ ExchangeFrame([]byte) ([]byte, error) }); ok {
			return exchanger.ExchangeFrame(frame)
		}
		return serviceReply(v, "", DispatchError("wrong_mode"))
	}
	return serviceReply(v, "", DispatchError("unknown_service"))
}

type Lending interface {
	Lend(store, object, engine string, copy_ bool) (LendResult, error)
	Unlend(entry string) (UnlendResult, error)
	Lends(continuation string, limit int64) (LendPage, error)
}
type LendingTransport interface {
	FrameExchanger
}
type LendingClient struct{ transport LendingTransport }

func NewLendingClient(t LendingTransport) *LendingClient { return &LendingClient{transport: t} }

type LendingDispatcher struct{ Handler Lending }

func (c *LendingClient) Lend(store, object, engine string, copy_ bool) (result LendResult, err error) {
	defer func() {
		if p := recover(); p != nil {
			if e, ok := p.(*Refusal); ok {
				err = e
			} else {
				panic(p)
			}
		}
	}()
	args := oaLendingLendArguments{Store: store, Object: object, Engine: engine, Copy: copy_}
	v := oaServiceFrame{Version: 1, Service: "abstraction.storage/lend@1", Method: "Lend", Arguments: Raw(encOALendingLendArguments(nil, &args, 1))}
	frame := encOAServiceFrame(nil, &v, 0)
	if _, err = servicePayload(frame); err != nil {
		return
	}
	var response []byte
	response, err = c.transport.ExchangeFrame(frame)
	if err != nil {
		return
	}
	var payload Raw
	payload, err = serviceResponse(response, v.Service, v.Method)
	if err != nil {
		return
	}
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	var decoded *oaLendingLendResult
	decoded, err = r.decodeOALendingLendResult()
	if err != nil {
		return
	}
	_ = decoded
	r.ws()
	if r.pos != len(r.buf) {
		err = r.refuse("trailing_bytes")
		return
	}
	result = decoded.Value
	return
}
func (c *LendingClient) Unlend(entry string) (result UnlendResult, err error) {
	defer func() {
		if p := recover(); p != nil {
			if e, ok := p.(*Refusal); ok {
				err = e
			} else {
				panic(p)
			}
		}
	}()
	args := oaLendingUnlendArguments{Entry: entry}
	v := oaServiceFrame{Version: 1, Service: "abstraction.storage/lend@1", Method: "Unlend", Arguments: Raw(encOALendingUnlendArguments(nil, &args, 1))}
	frame := encOAServiceFrame(nil, &v, 0)
	if _, err = servicePayload(frame); err != nil {
		return
	}
	var response []byte
	response, err = c.transport.ExchangeFrame(frame)
	if err != nil {
		return
	}
	var payload Raw
	payload, err = serviceResponse(response, v.Service, v.Method)
	if err != nil {
		return
	}
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	var decoded *oaLendingUnlendResult
	decoded, err = r.decodeOALendingUnlendResult()
	if err != nil {
		return
	}
	_ = decoded
	r.ws()
	if r.pos != len(r.buf) {
		err = r.refuse("trailing_bytes")
		return
	}
	result = decoded.Value
	return
}
func (c *LendingClient) Lends(continuation string, limit int64) (result LendPage, err error) {
	defer func() {
		if p := recover(); p != nil {
			if e, ok := p.(*Refusal); ok {
				err = e
			} else {
				panic(p)
			}
		}
	}()
	args := oaLendingLendsArguments{Continuation: continuation, Limit: limit}
	v := oaServiceFrame{Version: 1, Service: "abstraction.storage/lend@1", Method: "Lends", Arguments: Raw(encOALendingLendsArguments(nil, &args, 1))}
	frame := encOAServiceFrame(nil, &v, 0)
	if _, err = servicePayload(frame); err != nil {
		return
	}
	var response []byte
	response, err = c.transport.ExchangeFrame(frame)
	if err != nil {
		return
	}
	var payload Raw
	payload, err = serviceResponse(response, v.Service, v.Method)
	if err != nil {
		return
	}
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	var decoded *oaLendingLendsResult
	decoded, err = r.decodeOALendingLendsResult()
	if err != nil {
		return
	}
	_ = decoded
	r.ws()
	if r.pos != len(r.buf) {
		err = r.refuse("trailing_bytes")
		return
	}
	result = decoded.Value
	return
}

// DescribeService is this dispatcher's service as abstraction.facade/endpoint@1 Describe lists it:
// ready unless its handler implements Ready() (bool, string) and reports otherwise.
func (d *LendingDispatcher) DescribeService() (contract string, ready bool, why string) {
	if h, ok := d.Handler.(interface{ Ready() (bool, string) }); ok {
		if ready, why = h.Ready(); ready {
			why = ""
		}
		return "abstraction.storage/lend@1", ready, why
	}
	return "abstraction.storage/lend@1", true, ""
}

// DescribeServiceMetadata returns optional handler display facts for Describe.
// They grant no authority and do not change service admission.
func (d *LendingDispatcher) DescribeServiceMetadata() (guarantees []string, capabilities map[string]string) {
	if h, ok := d.Handler.(interface {
		DescribeMetadata() ([]string, map[string]string)
	}); ok {
		return h.DescribeMetadata()
	}
	return nil, nil
}

// ServiceContract is the wire name ServeEndpoint routes this dispatcher's frames by.
func (d *LendingDispatcher) ServiceContract() string { return "abstraction.storage/lend@1" }
func (d *LendingDispatcher) WriteFrame(frame []byte) error {
	v, err := servicePayload(frame)
	if err != nil {
		return err
	}
	if v.Service != "abstraction.storage/lend@1" {
		return DispatchError("unknown_service")
	}
	switch v.Method {
	case "Lend":
		return DispatchError("wrong_mode")
	case "Unlend":
		return DispatchError("wrong_mode")
	case "Lends":
		return DispatchError("wrong_mode")
	default:
		return DispatchError("unknown_method")
	}
}
func (d *LendingDispatcher) ExchangeFrame(frame []byte) ([]byte, error) {
	v, err := servicePayload(frame)
	if err != nil {
		return nil, err
	}
	if v.Service == EndpointContract {
		return DescribeEndpoint(frame, "", "", d)
	}
	if v.Service != "abstraction.storage/lend@1" {
		return serviceReply(v, "", DispatchError("unknown_service"))
	}
	switch v.Method {
	case "Lend":
		r := &reader{buf: []byte(v.Arguments), depth: 1}
		r.ws()
		args, err := r.decodeOALendingLendArguments()
		if err != nil {
			return serviceReply(v, "", err)
		}
		r.ws()
		if r.pos != len(r.buf) {
			return serviceReply(v, "", r.refuse("trailing_bytes"))
		}
		payload, err := d.invokeLend(args)
		return serviceReply(v, payload, err)
	case "Unlend":
		r := &reader{buf: []byte(v.Arguments), depth: 1}
		r.ws()
		args, err := r.decodeOALendingUnlendArguments()
		if err != nil {
			return serviceReply(v, "", err)
		}
		r.ws()
		if r.pos != len(r.buf) {
			return serviceReply(v, "", r.refuse("trailing_bytes"))
		}
		payload, err := d.invokeUnlend(args)
		return serviceReply(v, payload, err)
	case "Lends":
		r := &reader{buf: []byte(v.Arguments), depth: 1}
		r.ws()
		args, err := r.decodeOALendingLendsArguments()
		if err != nil {
			return serviceReply(v, "", err)
		}
		r.ws()
		if r.pos != len(r.buf) {
			return serviceReply(v, "", r.refuse("trailing_bytes"))
		}
		payload, err := d.invokeLends(args)
		return serviceReply(v, payload, err)
	default:
		return serviceReply(v, "", DispatchError("unknown_method"))
	}
}
func (d *LendingDispatcher) invokeLend(args *oaLendingLendArguments) (payload Raw, err error) {
	defer func() {
		if p := recover(); p != nil {
			payload = ""
			if _, ok := p.(*Refusal); ok {
				err = &ServiceError{Code: ServiceErrorCodeInvalidResult}
			} else {
				err = &ServiceError{Code: ServiceErrorCodeHandlerError, Message: "handler failed"}
			}
		}
	}()
	var result LendResult
	result, err = d.Handler.Lend(args.Store, args.Object, args.Engine, args.Copy)
	if err != nil {
		return
	}
	value := oaLendingLendResult{Value: result}
	payload = Raw(encOALendingLendResult(nil, &value, 1))
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	if _, e := r.decodeOALendingLendResult(); e != nil {
		payload = ""
		err = &ServiceError{Code: ServiceErrorCodeInvalidResult}
		return
	}
	r.ws()
	if r.pos != len(r.buf) {
		payload = ""
		err = &ServiceError{Code: ServiceErrorCodeInvalidResult}
	}
	return
}
func (d *LendingDispatcher) invokeUnlend(args *oaLendingUnlendArguments) (payload Raw, err error) {
	defer func() {
		if p := recover(); p != nil {
			payload = ""
			if _, ok := p.(*Refusal); ok {
				err = &ServiceError{Code: ServiceErrorCodeInvalidResult}
			} else {
				err = &ServiceError{Code: ServiceErrorCodeHandlerError, Message: "handler failed"}
			}
		}
	}()
	var result UnlendResult
	result, err = d.Handler.Unlend(args.Entry)
	if err != nil {
		return
	}
	value := oaLendingUnlendResult{Value: result}
	payload = Raw(encOALendingUnlendResult(nil, &value, 1))
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	if _, e := r.decodeOALendingUnlendResult(); e != nil {
		payload = ""
		err = &ServiceError{Code: ServiceErrorCodeInvalidResult}
		return
	}
	r.ws()
	if r.pos != len(r.buf) {
		payload = ""
		err = &ServiceError{Code: ServiceErrorCodeInvalidResult}
	}
	return
}
func (d *LendingDispatcher) invokeLends(args *oaLendingLendsArguments) (payload Raw, err error) {
	defer func() {
		if p := recover(); p != nil {
			payload = ""
			if _, ok := p.(*Refusal); ok {
				err = &ServiceError{Code: ServiceErrorCodeInvalidResult}
			} else {
				err = &ServiceError{Code: ServiceErrorCodeHandlerError, Message: "handler failed"}
			}
		}
	}()
	var result LendPage
	result, err = d.Handler.Lends(args.Continuation, args.Limit)
	if err != nil {
		return
	}
	value := oaLendingLendsResult{Value: result}
	payload = Raw(encOALendingLendsResult(nil, &value, 1))
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	if _, e := r.decodeOALendingLendsResult(); e != nil {
		payload = ""
		err = &ServiceError{Code: ServiceErrorCodeInvalidResult}
		return
	}
	r.ws()
	if r.pos != len(r.buf) {
		payload = ""
		err = &ServiceError{Code: ServiceErrorCodeInvalidResult}
	}
	return
}
