// Code generated by abstraction-idl from abstraction-storage/content.thrift. DO NOT EDIT.

#![allow(dead_code)]

use std::collections::BTreeMap;

// An opaque payload is bytes the contract forbids us to reinterpret, and String
// would refuse to hold one that is not UTF-8 rather than carry it back out.
pub type Raw = Vec<u8>;

const HEX: &[u8; 16] = b"0123456789abcdef";

fn esc_byte(out: &mut Vec<u8>, c: u8) {
    match c {
        b'"' => out.extend_from_slice(b"\\\""),
        b'\\' => out.extend_from_slice(b"\\\\"),
        0x08 => out.extend_from_slice(b"\\b"),
        0x0c => out.extend_from_slice(b"\\f"),
        b'\n' => out.extend_from_slice(b"\\n"),
        b'\r' => out.extend_from_slice(b"\\r"),
        b'\t' => out.extend_from_slice(b"\\t"),
        _ if c < 0x20 => {
            out.extend_from_slice(b"\\u00");
            out.push(HEX[(c >> 4) as usize]);
            out.push(HEX[(c & 0x0F) as usize]);
        }
        _ => out.push(c),
    }
}

pub fn num(out: &mut Vec<u8>, n: i64) {
    out.extend_from_slice(n.to_string().as_bytes());
}

pub fn pad(out: &mut Vec<u8>, depth: i32) {
    for _ in 0..depth * 2 {
        out.push(b' ');
    }
}

pub fn strs(out: &mut Vec<u8>, v: &[String], depth: i32) {
    if v.is_empty() {
        out.extend_from_slice(b"[]");
        return;
    }
    out.extend_from_slice(b"[\n");
    for (i, s) in v.iter().enumerate() {
        pad(out, depth + 1);
        esc(out, s);
        if i + 1 < v.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b']');
}

fn ws(c: u8) -> bool {
    c == b' ' || c == b'\t' || c == b'\n' || c == b'\r'
}

pub fn raw(out: &mut Vec<u8>, b: &[u8], depth: i32) {
    let mut depth = depth;
    let mut i = 0;
    while i < b.len() {
        let c = b[i];
        if ws(c) {
            i += 1;
        } else if c == b'"' {
            let mut j = i + 1;
            while j < b.len() {
                if b[j] == b'\\' {
                    j += 2;
                    continue;
                }
                if b[j] == b'"' {
                    j += 1;
                    break;
                }
                j += 1;
            }
            out.extend_from_slice(&b[i..j]);
            i = j;
        } else if c == b'{' || c == b'[' {
            out.push(c);
            i += 1;
            let mut j = i;
            while j < b.len() && ws(b[j]) {
                j += 1;
            }
            if j < b.len() && (b[j] == b'}' || b[j] == b']') {
                out.push(b[j]);
                i = j + 1;
            } else {
                depth += 1;
                out.push(b'\n');
                pad(out, depth);
            }
        } else if c == b'}' || c == b']' {
            depth -= 1;
            out.push(b'\n');
            pad(out, depth);
            out.push(c);
            i += 1;
        } else if c == b',' {
            out.extend_from_slice(b",\n");
            pad(out, depth);
            i += 1;
        } else if c == b':' {
            out.extend_from_slice(b": ");
            i += 1;
        } else {
            out.push(c);
            i += 1;
        }
    }
}

// A BTreeMap<String, _> walks its keys in String's Ord, which compares the
// UTF-8 bytes — the order the definition declares. Nothing sorts here.
pub fn rawmap(out: &mut Vec<u8>, m: &BTreeMap<String, Raw>, depth: i32) {
    if m.is_empty() {
        out.extend_from_slice(b"{}");
        return;
    }
    out.extend_from_slice(b"{\n");
    for (i, (k, v)) in m.iter().enumerate() {
        pad(out, depth + 1);
        esc(out, k);
        out.extend_from_slice(b": ");
        raw(out, v, depth + 1);
        if i + 1 < m.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b'}');
}

pub fn esc(out: &mut Vec<u8>, s: &str) {
    out.push(b'"');
    for c in s.as_bytes() {
        esc_byte(out, *c);
    }
    out.push(b'"');
}

pub const VERIFICATION_NAMES: [&str; 1] = ["unverified"];
pub const VERIFICATION_UNKNOWN: &str = "refuse";

pub const OPENOUTCOME_NAMES: [&str; 7] = ["opened", "not_found", "forbidden", "invalid", "unsupported", "unavailable", "exhausted"];
pub const OPENOUTCOME_UNKNOWN: &str = "refuse";

pub const READOUTCOME_NAMES: [&str; 6] = ["data", "gap", "forbidden", "invalid", "unavailable", "changed"];
pub const READOUTCOME_UNKNOWN: &str = "refuse";

pub const CLOSEOUTCOME_NAMES: [&str; 3] = ["closed", "gap", "forbidden"];
pub const CLOSEOUTCOME_UNKNOWN: &str = "refuse";

#[derive(Default)]
pub struct Resource {
    pub handle: String,
    pub digest: String,
    pub size: i64,
    pub verification: String,
}

#[derive(Default)]
pub struct OpenResult {
    pub outcome: String,
    pub resource: Option<Resource>,
}

#[derive(Default)]
pub struct Chunk {
    pub offset: i64,
    pub total: i64,
    pub data: Vec<u8>,
    pub eof: bool,
}

#[derive(Default)]
pub struct ReadResult {
    pub outcome: String,
    pub chunk: Option<Chunk>,
}

#[derive(Default)]
pub struct CloseResult {
    pub outcome: String,
}

#[derive(Default)]
pub struct OAContentReaderOpenArguments {
    pub digest: String,
}

#[derive(Default)]
pub struct OAContentReaderReadArguments {
    pub handle: String,
    pub offset: i64,
    pub max_bytes: i64,
}

#[derive(Default)]
pub struct OAContentReaderCloseArguments {
    pub handle: String,
}

#[derive(Default)]
pub struct OAServiceFrame {
    pub version: i32,
    pub service: String,
    pub method: String,
    pub arguments: Raw,
}

#[derive(Default)]
pub struct OAServiceReply {
    pub version: i32,
    pub service: String,
    pub method: String,
    pub ok: bool,
    pub payload: Raw,
}

#[derive(Default)]
pub struct OAServiceError {
    pub code: String,
    pub message: String,
}

#[derive(Default)]
pub struct OAContentReaderOpenResult {
    pub value: OpenResult,
}

#[derive(Default)]
pub struct OAContentReaderReadResult {
    pub value: ReadResult,
}

#[derive(Default)]
pub struct OAContentReaderCloseResult {
    pub value: CloseResult,
}

pub fn enc_resource(out: &mut Vec<u8>, v: &Resource, depth: i32) {
    if v.verification != "unverified" { std::panic::panic_any(Refusal{word:"bad_enum",offset:0}); }
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "handle");
    out.extend_from_slice(b": ");
    esc(out, &v.handle);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "digest");
    out.extend_from_slice(b": ");
    esc(out, &v.digest);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "size");
    out.extend_from_slice(b": ");
    num(out, v.size);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "verification");
    out.extend_from_slice(b": ");
    esc(out, &v.verification);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_openresult(out: &mut Vec<u8>, v: &OpenResult, depth: i32) {
    if v.outcome != "opened" && v.outcome != "not_found" && v.outcome != "forbidden" && v.outcome != "invalid" && v.outcome != "unsupported" && v.outcome != "unavailable" && v.outcome != "exhausted" { std::panic::panic_any(Refusal{word:"bad_enum",offset:0}); }
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "outcome");
    out.extend_from_slice(b": ");
    esc(out, &v.outcome);
    if v.resource.is_some() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "resource");
        out.extend_from_slice(b": ");
        enc_resource(out, v.resource.as_ref().unwrap(), depth + 1);
    }
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_chunk(out: &mut Vec<u8>, v: &Chunk, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "offset");
    out.extend_from_slice(b": ");
    num(out, v.offset);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "total");
    out.extend_from_slice(b": ");
    num(out, v.total);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "data");
    out.extend_from_slice(b": ");
    esc(out, &encode_binary(&v.data));
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "eof");
    out.extend_from_slice(b": ");
    out.extend_from_slice(if v.eof { b"true" } else { b"false" });
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_readresult(out: &mut Vec<u8>, v: &ReadResult, depth: i32) {
    if v.outcome != "data" && v.outcome != "gap" && v.outcome != "forbidden" && v.outcome != "invalid" && v.outcome != "unavailable" && v.outcome != "changed" { std::panic::panic_any(Refusal{word:"bad_enum",offset:0}); }
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "outcome");
    out.extend_from_slice(b": ");
    esc(out, &v.outcome);
    if v.chunk.is_some() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "chunk");
        out.extend_from_slice(b": ");
        enc_chunk(out, v.chunk.as_ref().unwrap(), depth + 1);
    }
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_closeresult(out: &mut Vec<u8>, v: &CloseResult, depth: i32) {
    if v.outcome != "closed" && v.outcome != "gap" && v.outcome != "forbidden" { std::panic::panic_any(Refusal{word:"bad_enum",offset:0}); }
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "outcome");
    out.extend_from_slice(b": ");
    esc(out, &v.outcome);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oacontentreaderopenarguments(out: &mut Vec<u8>, v: &OAContentReaderOpenArguments, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "digest");
    out.extend_from_slice(b": ");
    esc(out, &v.digest);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oacontentreaderreadarguments(out: &mut Vec<u8>, v: &OAContentReaderReadArguments, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "handle");
    out.extend_from_slice(b": ");
    esc(out, &v.handle);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "offset");
    out.extend_from_slice(b": ");
    num(out, v.offset);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "max_bytes");
    out.extend_from_slice(b": ");
    num(out, v.max_bytes);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oacontentreaderclosearguments(out: &mut Vec<u8>, v: &OAContentReaderCloseArguments, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "handle");
    out.extend_from_slice(b": ");
    esc(out, &v.handle);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaserviceframe(out: &mut Vec<u8>, v: &OAServiceFrame, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "version");
    out.extend_from_slice(b": ");
    num(out, v.version as i64);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "service");
    out.extend_from_slice(b": ");
    esc(out, &v.service);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "method");
    out.extend_from_slice(b": ");
    esc(out, &v.method);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "arguments");
    out.extend_from_slice(b": ");
    out.extend_from_slice(&v.arguments);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaservicereply(out: &mut Vec<u8>, v: &OAServiceReply, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "version");
    out.extend_from_slice(b": ");
    num(out, v.version as i64);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "service");
    out.extend_from_slice(b": ");
    esc(out, &v.service);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "method");
    out.extend_from_slice(b": ");
    esc(out, &v.method);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "ok");
    out.extend_from_slice(b": ");
    out.extend_from_slice(if v.ok { b"true" } else { b"false" });
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "payload");
    out.extend_from_slice(b": ");
    out.extend_from_slice(&v.payload);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaserviceerror(out: &mut Vec<u8>, v: &OAServiceError, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "code");
    out.extend_from_slice(b": ");
    esc(out, &v.code);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "message");
    out.extend_from_slice(b": ");
    esc(out, &v.message);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oacontentreaderopenresult(out: &mut Vec<u8>, v: &OAContentReaderOpenResult, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "value");
    out.extend_from_slice(b": ");
    enc_openresult(out, &v.value, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oacontentreaderreadresult(out: &mut Vec<u8>, v: &OAContentReaderReadResult, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "value");
    out.extend_from_slice(b": ");
    enc_readresult(out, &v.value, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oacontentreadercloseresult(out: &mut Vec<u8>, v: &OAContentReaderCloseResult, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "value");
    out.extend_from_slice(b": ");
    enc_closeresult(out, &v.value, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn encode(v: &OpenResult) -> Vec<u8> {
    let mut out = Vec::new();
    enc_openresult(&mut out, v, 0);
    out.push(b'\n');
    out
}

const DEPTH_LIMIT: i32 = 64;

#[derive(Debug)]
pub struct Refusal {
    pub word: &'static str,
    pub offset: usize,
}

impl std::fmt::Display for Refusal {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "refused: {} at byte {}", self.word, self.offset)
    }
}

impl std::error::Error for Refusal {}

fn append_rune(out: &mut Vec<u8>, cp: u32) {
    if cp < 0x80 {
        out.push(cp as u8);
    } else if cp < 0x800 {
        out.push(0xC0 | (cp >> 6) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    } else if cp < 0x10000 {
        out.push(0xE0 | (cp >> 12) as u8);
        out.push(0x80 | ((cp >> 6) & 0x3F) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    } else {
        out.push(0xF0 | (cp >> 18) as u8);
        out.push(0x80 | ((cp >> 12) & 0x3F) as u8);
        out.push(0x80 | ((cp >> 6) & 0x3F) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    }
}

struct Reader<'a> {
    buf: &'a [u8],
    pos: usize,
    depth: i32,
}

impl<'a> Reader<'a> {
    fn refuse<T>(&self, word: &'static str) -> Result<T, Refusal> {
        Err(Refusal { word, offset: self.pos })
    }

    fn at(&self) -> u8 {
        if self.pos < self.buf.len() { self.buf[self.pos] } else { 0 }
    }

    fn skip_ws(&mut self) {
        while self.pos < self.buf.len() && ws(self.buf[self.pos]) {
            self.pos += 1;
        }
    }

    fn enter(&mut self) -> Result<(), Refusal> {
        self.depth += 1;
        if self.depth > DEPTH_LIMIT {
            return self.refuse("depth_exceeded");
        }
        Ok(())
    }

    fn string(&mut self) -> Result<String, Refusal> {
        if self.at() != b'"' {
            return self.refuse("wrong_type");
        }
        self.pos += 1;
        let mut out: Vec<u8> = Vec::new();
        loop {
            if self.pos >= self.buf.len() {
                return self.refuse("malformed");
            }
            let c = self.buf[self.pos];
            if c == b'"' {
                self.pos += 1;
                return match String::from_utf8(out) {
                    Ok(s) => Ok(s),
                    Err(_) => self.refuse("bad_string"),
                };
            }
            if c < 0x20 {
                return self.refuse("bad_string");
            }
            if c == b'\\' {
                self.escape(&mut out)?;
            } else {
                out.push(c);
                self.pos += 1;
            }
        }
    }

    fn escape(&mut self, out: &mut Vec<u8>) -> Result<(), Refusal> {
        self.pos += 1;
        if self.pos >= self.buf.len() {
            return self.refuse("malformed");
        }
        let c = self.buf[self.pos];
        self.pos += 1;
        match c {
            b'"' | b'\\' | b'/' => out.push(c),
            b'b' => out.push(0x08),
            b'f' => out.push(0x0c),
            b'n' => out.push(b'\n'),
            b'r' => out.push(b'\r'),
            b't' => out.push(b'\t'),
            b'u' => {
                let mut u = self.hex4()?;
                if (0xDC00..=0xDFFF).contains(&u) {
                    return self.refuse("bad_string");
                }
                if (0xD800..=0xDBFF).contains(&u) {
                    if self.pos + 1 >= self.buf.len()
                        || self.buf[self.pos] != b'\\'
                        || self.buf[self.pos + 1] != b'u'
                    {
                        return self.refuse("bad_string");
                    }
                    self.pos += 2;
                    let low = self.hex4()?;
                    if !(0xDC00..=0xDFFF).contains(&low) {
                        return self.refuse("bad_string");
                    }
                    u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00);
                }
                append_rune(out, u);
            }
            _ => return self.refuse("bad_string"),
        }
        Ok(())
    }

    fn hex4(&mut self) -> Result<u32, Refusal> {
        if self.pos + 4 > self.buf.len() {
            return self.refuse("bad_string");
        }
        let mut u: u32 = 0;
        for i in 0..4 {
            let c = self.buf[self.pos + i];
            let d = match c {
                b'0'..=b'9' => c - b'0',
                b'a'..=b'f' => c - b'a' + 10,
                b'A'..=b'F' => c - b'A' + 10,
                _ => return self.refuse("bad_string"),
            };
            u = u << 4 | d as u32;
        }
        self.pos += 4;
        Ok(u)
    }

    fn integer(&mut self, low: i64, high: i64) -> Result<i64, Refusal> {
        let c = self.at();
        if c != b'-' && !c.is_ascii_digit() {
            return self.refuse("wrong_type");
        }
        let negative = c == b'-';
        if negative {
            self.pos += 1;
        }
        if !self.at().is_ascii_digit() {
            return self.refuse("malformed");
        }
        let mut u: u64 = 0;
        if self.at() == b'0' {
            self.pos += 1;
        } else {
            while self.at().is_ascii_digit() {
                if u > 922337203685477580 {
                    return self.refuse("number_spelling");
                }
                u = u * 10 + (self.at() - b'0') as u64;
                self.pos += 1;
            }
        }
        let after = self.at();
        if after == b'.' || after == b'e' || after == b'E' || after.is_ascii_digit() {
            return self.refuse("number_spelling");
        }
        if negative && u == 0 {
            return self.refuse("number_spelling");
        }
        let n = if negative {
            if u > 1u64 << 63 {
                return self.refuse("number_spelling");
            }
            if u == 1u64 << 63 { i64::MIN } else { -(u as i64) }
        } else {
            if u > i64::MAX as u64 {
                return self.refuse("number_spelling");
            }
            u as i64
        };
        if n < low || n > high {
            return self.refuse("number_spelling");
        }
        Ok(n)
    }

    fn boolean(&mut self) -> Result<bool, Refusal> {
        match self.at() {
            b't' => {
                self.literal(b"true")?;
                Ok(true)
            }
            b'f' => {
                self.literal(b"false")?;
                Ok(false)
            }
            _ => self.refuse("wrong_type"),
        }
    }

    fn literal(&mut self, word: &[u8]) -> Result<(), Refusal> {
        if self.pos + word.len() > self.buf.len() || &self.buf[self.pos..self.pos + word.len()] != word {
            return self.refuse("malformed");
        }
        self.pos += word.len();
        Ok(())
    }

    fn str_list(&mut self) -> Result<Vec<String>, Refusal> {
        if self.at() != b'[' {
            return self.refuse("wrong_type");
        }
        self.enter()?;
        self.pos += 1;
        let mut out = Vec::new();
        self.skip_ws();
        if self.at() != b']' {
            loop {
                self.skip_ws();
                out.push(self.string()?);
                self.skip_ws();
                if self.at() != b',' {
                    break;
                }
                self.pos += 1;
            }
        }
        if self.at() != b']' {
            return self.refuse("malformed");
        }
        self.pos += 1;
        self.depth -= 1;
        Ok(out)
    }

    fn raw_map(&mut self) -> Result<BTreeMap<String, Raw>, Refusal> {
        if self.at() != b'{' {
            return self.refuse("wrong_type");
        }
        self.enter()?;
        self.pos += 1;
        let mut out = BTreeMap::new();
        self.skip_ws();
        if self.at() != b'}' {
            loop {
                self.skip_ws();
                if self.at() != b'"' {
                    return self.refuse("malformed");
                }
                let k = self.string()?;
                if out.contains_key(&k) {
                    return self.refuse("duplicate_key");
                }
                self.skip_ws();
                if self.at() != b':' {
                    return self.refuse("malformed");
                }
                self.pos += 1;
                self.skip_ws();
                let v = self.raw_value()?;
                out.insert(k, v);
                self.skip_ws();
                if self.at() != b',' {
                    break;
                }
                self.pos += 1;
            }
        }
        if self.at() != b'}' {
            return self.refuse("malformed");
        }
        self.pos += 1;
        self.depth -= 1;
        Ok(out)
    }

    fn raw_value(&mut self) -> Result<Raw, Refusal> {
        let start = self.pos;
        self.skip_value()?;
        Ok(self.buf[start..self.pos].to_vec())
    }

    fn skip_value(&mut self) -> Result<(), Refusal> {
        let c = self.at();
        match c {
            b'"' => self.skip_string(),
            b'{' | b'[' => self.skip_container(),
            b't' => self.literal(b"true"),
            b'f' => self.literal(b"false"),
            b'n' => self.literal(b"null"),
            b'-' => self.skip_number(),
            _ if c.is_ascii_digit() => self.skip_number(),
            _ => self.refuse("malformed"),
        }
    }

    // An opaque value is validated and carried, never interpreted. Its syntax is
    // the record's own — the same string reader, so an escape, a control byte or
    // a lone surrogate is judged identically at any depth — and what it is free
    // to spell, it keeps: the bytes between these two offsets are what a writer
    // re-emits. A number is walked, never converted, so a value no host type
    // holds survives the reader that carried it.
    fn skip_string(&mut self) -> Result<(), Refusal> {
        self.string()?;
        Ok(())
    }

    fn some_digits(&mut self) -> Result<(), Refusal> {
        let mut n = 0;
        while self.at().is_ascii_digit() {
            self.pos += 1;
            n += 1;
        }
        if n == 0 {
            return self.refuse("number_spelling");
        }
        Ok(())
    }

    fn skip_number(&mut self) -> Result<(), Refusal> {
        if self.at() == b'-' {
            self.pos += 1;
        }
        match self.at() {
            b'0' => self.pos += 1,
            c if c.is_ascii_digit() => {
                while self.at().is_ascii_digit() {
                    self.pos += 1;
                }
            }
            _ => return self.refuse("number_spelling"),
        }
        if self.at() == b'.' {
            self.pos += 1;
            self.some_digits()?;
        }
        if self.at() == b'e' || self.at() == b'E' {
            self.pos += 1;
            if self.at() == b'+' || self.at() == b'-' {
                self.pos += 1;
            }
            self.some_digits()?;
        }
        Ok(())
    }

    fn skip_container(&mut self) -> Result<(), Refusal> {
        let opener = self.at();
        let shut = if opener == b'{' { b'}' } else { b']' };
        self.enter()?;
        self.pos += 1;
        self.skip_ws();
        let mut seen: BTreeMap<String, bool> = BTreeMap::new();
        if self.at() != shut {
            loop {
                self.skip_ws();
                if opener == b'{' {
                    if self.at() != b'"' {
                        return self.refuse("malformed");
                    }
                    let k = self.string()?;
                    if seen.insert(k, true).is_some() {
                        return self.refuse("duplicate_key");
                    }
                    self.skip_ws();
                    if self.at() != b':' {
                        return self.refuse("malformed");
                    }
                    self.pos += 1;
                    self.skip_ws();
                }
                self.skip_value()?;
                self.skip_ws();
                if self.at() != b',' {
                    break;
                }
                self.pos += 1;
            }
        }
        if self.at() != shut {
            return self.refuse("malformed");
        }
        self.pos += 1;
        self.depth -= 1;
        Ok(())
    }
}

fn encode_binary(value: &[u8]) -> String {
    const ALPHABET: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::new();
    for chunk in value.chunks(3) {
        let mut v = (chunk[0] as u32) << 16;
        if chunk.len() > 1 { v |= (chunk[1] as u32) << 8; }
        if chunk.len() > 2 { v |= chunk[2] as u32; }
        out.push(ALPHABET[(v >> 18) as usize] as char);
        out.push(ALPHABET[((v >> 12) & 63) as usize] as char);
        out.push(if chunk.len() > 1 { ALPHABET[((v >> 6) & 63) as usize] as char } else { '=' });
        out.push(if chunk.len() > 2 { ALPHABET[(v & 63) as usize] as char } else { '=' });
    }
    out
}
fn read_binary(r: &mut Reader) -> Result<Vec<u8>, Refusal> {
    let text = r.string()?;
    let bytes = text.as_bytes();
    if bytes.len() % 4 != 0 { return r.refuse("bad_binary"); }
    let mut out = Vec::new();
    for (i, chunk) in bytes.chunks(4).enumerate() {
        let mut v = 0u32;
        let mut pad = 0;
        for (j, &c) in chunk.iter().enumerate() {
            let digit = if c == b'=' {
                if j < 2 || (i + 1) * 4 != bytes.len() { return r.refuse("bad_binary"); }
                pad += 1;
                0
            } else {
                if pad != 0 { return r.refuse("bad_binary"); }
                match c {
                    b'A'..=b'Z' => c - b'A',
                    b'a'..=b'z' => c - b'a' + 26,
                    b'0'..=b'9' => c - b'0' + 52,
                    b'+' => 62,
                    b'/' => 63,
                    _ => return r.refuse("bad_binary"),
                }
            };
            v = (v << 6) | digit as u32;
        }
        out.push((v >> 16) as u8);
        if pad < 2 { out.push((v >> 8) as u8); }
        if pad == 0 { out.push(v as u8); }
    }
    if encode_binary(&out) != text { return r.refuse("bad_binary"); }
    Ok(out)
}

fn decode_resource(r: &mut Reader) -> Result<Resource, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = Resource::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "handle" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.handle = r.string()?;
                }
                "digest" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.digest = r.string()?;
                }
                "size" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.size = r.integer(i64::MIN, i64::MAX)?;
                }
                "verification" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.verification = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 15 != 15 {
        return r.refuse("missing_field");
    }
    if v.verification != "unverified" { return r.refuse("bad_enum"); }
    Ok(v)
}

fn decode_openresult(r: &mut Reader) -> Result<OpenResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OpenResult::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "outcome" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.outcome = r.string()?;
                }
                "resource" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.resource = Some(decode_resource(r)?);
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    if v.outcome != "opened" && v.outcome != "not_found" && v.outcome != "forbidden" && v.outcome != "invalid" && v.outcome != "unsupported" && v.outcome != "unavailable" && v.outcome != "exhausted" { return r.refuse("bad_enum"); }
    Ok(v)
}

fn decode_chunk(r: &mut Reader) -> Result<Chunk, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = Chunk::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "offset" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.offset = r.integer(i64::MIN, i64::MAX)?;
                }
                "total" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.total = r.integer(i64::MIN, i64::MAX)?;
                }
                "data" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.data = read_binary(r)?;
                }
                "eof" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.eof = r.boolean()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 15 != 15 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_readresult(r: &mut Reader) -> Result<ReadResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = ReadResult::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "outcome" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.outcome = r.string()?;
                }
                "chunk" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.chunk = Some(decode_chunk(r)?);
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    if v.outcome != "data" && v.outcome != "gap" && v.outcome != "forbidden" && v.outcome != "invalid" && v.outcome != "unavailable" && v.outcome != "changed" { return r.refuse("bad_enum"); }
    Ok(v)
}

fn decode_closeresult(r: &mut Reader) -> Result<CloseResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = CloseResult::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "outcome" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.outcome = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    if v.outcome != "closed" && v.outcome != "gap" && v.outcome != "forbidden" { return r.refuse("bad_enum"); }
    Ok(v)
}

fn decode_oacontentreaderopenarguments(r: &mut Reader) -> Result<OAContentReaderOpenArguments, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAContentReaderOpenArguments::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "digest" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.digest = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oacontentreaderreadarguments(r: &mut Reader) -> Result<OAContentReaderReadArguments, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAContentReaderReadArguments::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "handle" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.handle = r.string()?;
                }
                "offset" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.offset = r.integer(i64::MIN, i64::MAX)?;
                }
                "max_bytes" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.max_bytes = r.integer(i64::MIN, i64::MAX)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 7 != 7 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oacontentreaderclosearguments(r: &mut Reader) -> Result<OAContentReaderCloseArguments, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAContentReaderCloseArguments::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "handle" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.handle = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaserviceframe(r: &mut Reader) -> Result<OAServiceFrame, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAServiceFrame::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "version" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.version = r.integer(-2147483648, 2147483647)? as i32;
                }
                "service" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.service = r.string()?;
                }
                "method" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.method = r.string()?;
                }
                "arguments" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.arguments = r.raw_value()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 15 != 15 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaservicereply(r: &mut Reader) -> Result<OAServiceReply, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAServiceReply::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "version" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.version = r.integer(-2147483648, 2147483647)? as i32;
                }
                "service" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.service = r.string()?;
                }
                "method" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.method = r.string()?;
                }
                "ok" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.ok = r.boolean()?;
                }
                "payload" => {
                    if seen & 16 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 16;
                    v.payload = r.raw_value()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 31 != 31 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaserviceerror(r: &mut Reader) -> Result<OAServiceError, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAServiceError::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "code" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.code = r.string()?;
                }
                "message" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.message = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oacontentreaderopenresult(r: &mut Reader) -> Result<OAContentReaderOpenResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAContentReaderOpenResult::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "value" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.value = decode_openresult(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oacontentreaderreadresult(r: &mut Reader) -> Result<OAContentReaderReadResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAContentReaderReadResult::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "value" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.value = decode_readresult(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oacontentreadercloseresult(r: &mut Reader) -> Result<OAContentReaderCloseResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAContentReaderCloseResult::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "value" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.value = decode_closeresult(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

pub fn decode(data: &[u8]) -> Result<OpenResult, Refusal> {
    let mut r = Reader { buf: data, pos: 0, depth: 0 };
    r.skip_ws();
    let v = decode_openresult(&mut r)?;
    r.skip_ws();
    if r.pos < r.buf.len() {
        return r.refuse("trailing_bytes");
    }
    Ok(v)
}

// REFUSALS is in the order two of them are chosen between.
pub const REFUSALS: [&str; 12] = ["malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_binary", "bad_enum", "trailing_bytes"];

pub fn refusal_rank(word: &str) -> i32 {
    match REFUSALS.iter().position(|w| *w == word) {
        Some(i) => i as i32,
        None => -1,
    }
}

#[allow(unused_variables)]
fn service_check_resource(v: &Resource) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    if v.verification != "unverified" { return r.refuse("bad_enum"); }
    Ok(())
}

#[allow(unused_variables)]
fn service_check_openresult(v: &OpenResult) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    if v.outcome != "opened" && v.outcome != "not_found" && v.outcome != "forbidden" && v.outcome != "invalid" && v.outcome != "unsupported" && v.outcome != "unavailable" && v.outcome != "exhausted" { return r.refuse("bad_enum"); }
    if let Some(value) = &v.resource { service_check_resource(value)?; }
    Ok(())
}

#[allow(unused_variables)]
fn service_check_chunk(v: &Chunk) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_readresult(v: &ReadResult) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    if v.outcome != "data" && v.outcome != "gap" && v.outcome != "forbidden" && v.outcome != "invalid" && v.outcome != "unavailable" && v.outcome != "changed" { return r.refuse("bad_enum"); }
    if let Some(value) = &v.chunk { service_check_chunk(value)?; }
    Ok(())
}

#[allow(unused_variables)]
fn service_check_closeresult(v: &CloseResult) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    if v.outcome != "closed" && v.outcome != "gap" && v.outcome != "forbidden" { return r.refuse("bad_enum"); }
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oacontentreaderopenarguments(v: &OAContentReaderOpenArguments) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oacontentreaderreadarguments(v: &OAContentReaderReadArguments) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oacontentreaderclosearguments(v: &OAContentReaderCloseArguments) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaserviceframe(v: &OAServiceFrame) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaservicereply(v: &OAServiceReply) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaserviceerror(v: &OAServiceError) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oacontentreaderopenresult(v: &OAContentReaderOpenResult) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_openresult(&v.value)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oacontentreaderreadresult(v: &OAContentReaderReadResult) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_readresult(&v.value)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oacontentreadercloseresult(v: &OAContentReaderCloseResult) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_closeresult(&v.value)?;
    Ok(())
}

/// Common generated framing boundary; implementation owns waiting and identity.
pub use abstraction_frame::FrameTransport;

#[derive(Debug)]
pub struct ServiceError { pub code: String, pub message: String }
#[derive(Debug)]
pub enum CallError<E> {
    /// Transport failure does not establish whether the receiver accepted work.
    Transport(E),
    Refusal(Refusal),
    Dispatch(&'static str),
    Service(ServiceError),
}
fn service_decode<T>(data: &[u8], decode: fn(&mut Reader) -> Result<T, Refusal>) -> Result<T, Refusal> {
    let mut r = Reader { buf: data, pos: 0, depth: 0 };
    r.skip_ws();
    let value = decode(&mut r)?;
    r.skip_ws();
    if r.pos != data.len() { return r.refuse("trailing_bytes"); }
    Ok(value)
}
fn service_encode<T>(value: &T, check: fn(&T) -> Result<(), Refusal>, encode: fn(&mut Vec<u8>, &T, i32), decode: fn(&mut Reader) -> Result<T, Refusal>) -> Result<Vec<u8>, Refusal> {
    check(value)?;
    let mut data = Vec::new();
    encode(&mut data, value, 0);
    service_decode(&data, decode)?;
    Ok(data)
}

#[allow(non_snake_case)]
pub trait ContentReader {
    type Error;
    fn Open(&self, arg0: String) -> Result<OpenResult, Self::Error>;
    fn Read(&self, arg0: String, arg1: i64, arg2: i64) -> Result<ReadResult, Self::Error>;
    fn Close(&self, arg0: String) -> Result<CloseResult, Self::Error>;
}

pub struct ContentReaderClient<T> { transport: T }
impl<T> ContentReaderClient<T> {
    pub fn new(transport: T) -> Self { Self { transport } }
    pub fn transport(&self) -> &T { &self.transport }
}
#[allow(non_snake_case)]
impl<T: FrameTransport> ContentReader for ContentReaderClient<T> {
    type Error = CallError<T::Error>;
    fn Open(&self, arg0: String) -> Result<OpenResult, Self::Error> {
        let args = OAContentReaderOpenArguments { digest: arg0, };
        let arguments = service_encode(&args, service_check_oacontentreaderopenarguments, enc_oacontentreaderopenarguments, decode_oacontentreaderopenarguments).map_err(CallError::Refusal)?;
        let request = OAServiceFrame { version: 1, service: "abstraction.storage/content-reader@1".into(), method: "Open".into(), arguments };
        let frame = service_encode(&request, service_check_oaserviceframe, enc_oaserviceframe, decode_oaserviceframe).map_err(CallError::Refusal)?;
        let reply = self.transport.exchange_frame(&frame).map_err(CallError::Transport)?;
        let reply = service_decode(&reply, decode_oaservicereply).map_err(CallError::Refusal)?;
        if reply.version != 1 { return Err(CallError::Dispatch("unknown_version")); }
        if reply.service != "abstraction.storage/content-reader@1" || reply.method != "Open" { return Err(CallError::Dispatch("mismatched_response")); }
        if !reply.ok {
            let error = service_decode(&reply.payload, decode_oaserviceerror).map_err(CallError::Refusal)?;
            if error.code.is_empty() { return Err(CallError::Dispatch("invalid_error")); }
            return Err(CallError::Service(ServiceError { code: error.code, message: error.message }));
        }
        let result = service_decode(&reply.payload, decode_oacontentreaderopenresult).map_err(CallError::Refusal)?;
        Ok(result.value)
    }
    fn Read(&self, arg0: String, arg1: i64, arg2: i64) -> Result<ReadResult, Self::Error> {
        let args = OAContentReaderReadArguments { handle: arg0, offset: arg1, max_bytes: arg2, };
        let arguments = service_encode(&args, service_check_oacontentreaderreadarguments, enc_oacontentreaderreadarguments, decode_oacontentreaderreadarguments).map_err(CallError::Refusal)?;
        let request = OAServiceFrame { version: 1, service: "abstraction.storage/content-reader@1".into(), method: "Read".into(), arguments };
        let frame = service_encode(&request, service_check_oaserviceframe, enc_oaserviceframe, decode_oaserviceframe).map_err(CallError::Refusal)?;
        let reply = self.transport.exchange_frame(&frame).map_err(CallError::Transport)?;
        let reply = service_decode(&reply, decode_oaservicereply).map_err(CallError::Refusal)?;
        if reply.version != 1 { return Err(CallError::Dispatch("unknown_version")); }
        if reply.service != "abstraction.storage/content-reader@1" || reply.method != "Read" { return Err(CallError::Dispatch("mismatched_response")); }
        if !reply.ok {
            let error = service_decode(&reply.payload, decode_oaserviceerror).map_err(CallError::Refusal)?;
            if error.code.is_empty() { return Err(CallError::Dispatch("invalid_error")); }
            return Err(CallError::Service(ServiceError { code: error.code, message: error.message }));
        }
        let result = service_decode(&reply.payload, decode_oacontentreaderreadresult).map_err(CallError::Refusal)?;
        Ok(result.value)
    }
    fn Close(&self, arg0: String) -> Result<CloseResult, Self::Error> {
        let args = OAContentReaderCloseArguments { handle: arg0, };
        let arguments = service_encode(&args, service_check_oacontentreaderclosearguments, enc_oacontentreaderclosearguments, decode_oacontentreaderclosearguments).map_err(CallError::Refusal)?;
        let request = OAServiceFrame { version: 1, service: "abstraction.storage/content-reader@1".into(), method: "Close".into(), arguments };
        let frame = service_encode(&request, service_check_oaserviceframe, enc_oaserviceframe, decode_oaserviceframe).map_err(CallError::Refusal)?;
        let reply = self.transport.exchange_frame(&frame).map_err(CallError::Transport)?;
        let reply = service_decode(&reply, decode_oaservicereply).map_err(CallError::Refusal)?;
        if reply.version != 1 { return Err(CallError::Dispatch("unknown_version")); }
        if reply.service != "abstraction.storage/content-reader@1" || reply.method != "Close" { return Err(CallError::Dispatch("mismatched_response")); }
        if !reply.ok {
            let error = service_decode(&reply.payload, decode_oaserviceerror).map_err(CallError::Refusal)?;
            if error.code.is_empty() { return Err(CallError::Dispatch("invalid_error")); }
            return Err(CallError::Service(ServiceError { code: error.code, message: error.message }));
        }
        let result = service_decode(&reply.payload, decode_oacontentreadercloseresult).map_err(CallError::Refusal)?;
        Ok(result.value)
    }
}
